import { getD1 } from "../../db";
import type { AuthContext } from "../auth/context";
import { HttpError } from "../auth/context";
import { contentHash, stableId } from "../core/ids";
import { calculatePortfolioRisk, correlationMatrix, generateActionConditions, stressPortfolio, type PortfolioPosition, type RiskPolicy, type Shock } from "./analytics";

type JsonRecord = Record<string, unknown>;

export async function getPortfolioWorkbench(context: AuthContext, requestedPortfolioId?: string | null) {
  const portfolio = await ensurePortfolio(context, requestedPortfolioId); const db = getD1();
  const rawPositions = await db.prepare("SELECT pp.id,pp.position_type AS positionType,pp.shares,pp.average_cost AS averageCost,pp.current_price AS currentPrice,pp.price_as_of AS priceAsOf,pp.market_value AS marketValue,pp.currency,pp.benchmark_weight AS benchmarkWeight,pp.beta,pp.daily_volatility AS dailyVolatility,pp.adv_usd AS advUsd,pp.sector,pp.industry,pp.factor_exposures_json AS factorExposuresJson,pp.event_tags_json AS eventTagsJson,pp.data_status AS dataStatus,s.id AS securityId,s.ticker,s.issuer_name AS issuerName FROM portfolio_positions pp JOIN securities s ON s.id=pp.security_id WHERE pp.workspace_id=? AND pp.portfolio_id=? ORDER BY CASE pp.position_type WHEN 'long' THEN 0 WHEN 'short' THEN 1 ELSE 2 END,ABS(COALESCE(pp.market_value,pp.shares*pp.current_price)) DESC").bind(context.workspaceId, portfolio.id).all<JsonRecord>();
  const watchItems = await db.prepare("SELECT s.id AS securityId,s.ticker,s.issuer_name AS issuerName FROM watchlist_items wi JOIN watchlists w ON w.id=wi.watchlist_id JOIN securities s ON s.id=wi.security_id WHERE w.workspace_id=? AND NOT EXISTS(SELECT 1 FROM portfolio_positions pp WHERE pp.portfolio_id=? AND pp.security_id=s.id) ORDER BY wi.priority DESC,wi.added_at").bind(context.workspaceId, portfolio.id).all<JsonRecord>();
  const policyRow = await db.prepare("SELECT nav,max_position_weight AS maxPositionWeight,max_sector_weight AS maxSectorWeight,max_factor_exposure AS maxFactorExposure,max_event_cluster_weight AS maxEventClusterWeight,scenario_loss_budget_bps AS scenarioLossBudgetBps,absolute_loss_cap_bps AS absoluteLossCapBps,correlation_lookback_days AS correlationLookbackDays,exit_participation_rate AS exitParticipationRate FROM portfolio_risk_policies WHERE workspace_id=? AND portfolio_id=?").bind(context.workspaceId, portfolio.id).first<JsonRecord>();
  const policy = parsePolicy(policyRow); const positions = rawPositions.results.map(parsePosition); const risk = calculatePortfolioRisk(positions, policy);
  const returns = await db.prepare("SELECT s.ticker,r.trading_date AS tradingDate,r.return_value AS returnValue FROM portfolio_return_series r JOIN securities s ON s.id=r.security_id WHERE r.workspace_id=? AND r.portfolio_id=? ORDER BY r.trading_date DESC LIMIT 10000").bind(context.workspaceId, portfolio.id).all<{ ticker: string; tradingDate: string; returnValue: number }>();
  const series = returns.results.reduce<Record<string, Record<string, number>>>((result, row) => { (result[row.ticker] ??= {})[row.tradingDate] = row.returnValue; return result; }, {});
  const correlation = correlationMatrix(series, Math.min(20, Math.max(3, Math.floor((policy.correlationLookbackDays ?? 60) / 3))));
  const theses = await latestThesisSignals(context.workspaceId, positions.map((position) => position.ticker));
  const latestScenario = await db.prepare("SELECT ps.id,ps.logical_id AS logicalId,ps.version,ps.name,ps.description,ps.shocks_json AS shocksJson,ps.status,ps.as_of AS asOf,pr.result_json AS resultJson FROM portfolio_scenarios ps LEFT JOIN portfolio_scenario_results pr ON pr.id=(SELECT x.id FROM portfolio_scenario_results x WHERE x.scenario_id=ps.id ORDER BY x.created_at DESC LIMIT 1) WHERE ps.workspace_id=? AND ps.portfolio_id=? AND ps.version=(SELECT MAX(x.version) FROM portfolio_scenarios x WHERE x.logical_id=ps.logical_id) ORDER BY ps.updated_at DESC LIMIT 20").bind(context.workspaceId, portfolio.id).all<JsonRecord>();
  const scenarios = latestScenario.results.map((row) => ({ ...row, shocks: safeArray(row.shocksJson), result: safeObject(row.resultJson) }));
  const scenarioLossBps = Math.max(0, ...scenarios.map((item) => Number((item.result as JsonRecord)?.lossBps ?? 0)));
  const generated = generateActionConditions(positions, policy, theses, scenarioLossBps);
  const savedConditions = await db.prepare("SELECT pac.id,pac.condition_type AS conditionType,pac.trigger_kind AS triggerKind,pac.severity,pac.message,pac.status,pac.predicate_json AS predicateJson,pac.as_of AS asOf,s.ticker FROM portfolio_action_conditions pac LEFT JOIN securities s ON s.id=pac.security_id WHERE pac.workspace_id=? AND pac.portfolio_id=? AND pac.status IN ('triggered','acknowledged') ORDER BY CASE pac.severity WHEN 'critical' THEN 0 ELSE 1 END,pac.updated_at DESC LIMIT 100").bind(context.workspaceId, portfolio.id).all<JsonRecord>();
  const catalysts = await db.prepare("SELECT c.id,s.ticker,c.title,c.event_type AS eventType,c.event_at AS eventAt,c.date_status AS dateStatus,c.status,c.as_of AS asOf,src.is_stale AS isStale FROM catalysts c JOIN securities s ON s.id=c.security_id JOIN portfolio_positions pp ON pp.security_id=c.security_id AND pp.portfolio_id=? LEFT JOIN sources src ON src.id=c.source_id WHERE c.workspace_id=? AND c.status='upcoming' ORDER BY CASE WHEN c.event_at IS NULL THEN 1 ELSE 0 END,c.event_at LIMIT 100").bind(portfolio.id, context.workspaceId).all<JsonRecord>();
  const portfolios = await db.prepare("SELECT id,name,base_currency AS baseCurrency,updated_at AS updatedAt FROM portfolios WHERE workspace_id=? ORDER BY updated_at DESC").bind(context.workspaceId).all<JsonRecord>();
  return { portfolios: portfolios.results, portfolio, positions, watchItems: watchItems.results, policy, risk, correlation, scenarios, catalysts: catalysts.results, theses, generatedConditions: generated, savedConditions: savedConditions.results.map((item) => ({ ...item, predicate: safeObject(item.predicateJson) })), asOf: new Date().toISOString(), executionPolicy: "conditions_only_no_order_execution" };
}

export async function mutatePortfolio(context: AuthContext, input: JsonRecord) {
  const action = requiredString(input.action, "action"); const now = new Date().toISOString(); const db = getD1();
  if (action === "portfolio.create") {
    const name = requiredString(input.name, "name", 80); const id = await stableId("por", `${context.workspaceId}:${name}:${crypto.randomUUID()}`);
    await db.prepare("INSERT INTO portfolios (id,workspace_id,name,base_currency,created_at,updated_at) VALUES (?,?,?,?,?,?)").bind(id, context.workspaceId, name, currency(input.baseCurrency), now, now).run();
    await ensurePortfolio(context, id); return { action, id };
  }
  const portfolio = await ensurePortfolio(context, optionalString(input.portfolioId));
  if (action === "position.save") {
    const ticker = requiredTicker(input.ticker); const security = await ensureSecurity(context.workspaceId, ticker, optionalString(input.issuerName)); const positionType = enumValue(input.positionType, ["long", "short", "watch"] as const, "long");
    const id = await stableId("pos", `${portfolio.id}:${security.id}:${positionType}`); const factors = numericObject(input.factorExposures); const events = stringArray(input.eventTags);
    await db.prepare("INSERT INTO portfolio_positions (id,workspace_id,portfolio_id,security_id,position_type,shares,average_cost,current_price,price_as_of,market_value,currency,benchmark_weight,beta,daily_volatility,adv_usd,sector,industry,factor_exposures_json,event_tags_json,data_status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(portfolio_id,security_id,position_type) DO UPDATE SET shares=excluded.shares,average_cost=excluded.average_cost,current_price=excluded.current_price,price_as_of=excluded.price_as_of,market_value=excluded.market_value,currency=excluded.currency,benchmark_weight=excluded.benchmark_weight,beta=excluded.beta,daily_volatility=excluded.daily_volatility,adv_usd=excluded.adv_usd,sector=excluded.sector,industry=excluded.industry,factor_exposures_json=excluded.factor_exposures_json,event_tags_json=excluded.event_tags_json,data_status=excluded.data_status,updated_at=excluded.updated_at").bind(id, context.workspaceId, portfolio.id, security.id, positionType, decimal(input.shares, 0, 1e15, 0), nullableDecimal(input.averageCost), nullableDecimal(input.currentPrice), validDate(input.priceAsOf) ?? now, nullableDecimal(input.marketValue), currency(input.currency), nullableDecimal(input.benchmarkWeight), nullableDecimal(input.beta), nullableDecimal(input.dailyVolatility), nullableDecimal(input.advUsd), optionalString(input.sector, 80), optionalString(input.industry, 120), JSON.stringify(factors), JSON.stringify(events), enumValue(input.dataStatus, ["current", "stale", "user_input", "missing"] as const, "user_input"), now, now).run();
    return { action, id, ticker };
  }
  if (action === "position.remove") { const id = requiredString(input.id, "id"); await db.prepare("DELETE FROM portfolio_positions WHERE id=? AND workspace_id=? AND portfolio_id=?").bind(id, context.workspaceId, portfolio.id).run(); return { action, id }; }
  if (action === "policy.save") {
    await db.prepare("UPDATE portfolio_risk_policies SET nav=?,max_position_weight=?,max_sector_weight=?,max_factor_exposure=?,max_event_cluster_weight=?,scenario_loss_budget_bps=?,absolute_loss_cap_bps=?,correlation_lookback_days=?,exit_participation_rate=?,updated_at=? WHERE workspace_id=? AND portfolio_id=?").bind(decimal(input.nav, 0, 1e18, 0), ratio(input.maxPositionWeight, .2), ratio(input.maxSectorWeight, .4), ratio(input.maxFactorExposure, .5), ratio(input.maxEventClusterWeight, .35), integer(input.scenarioLossBudgetBps, 1, 10000, 1000), integer(input.absoluteLossCapBps, 1, 10000, 2000), integer(input.correlationLookbackDays, 20, 756, 60), ratio(input.exitParticipationRate, .1), now, context.workspaceId, portfolio.id).run(); return { action, id: portfolio.id };
  }
  if (action === "returns.import") {
    const rows = Array.isArray(input.rows) ? input.rows.slice(0, 5000) : []; if (!rows.length) throw new HttpError(400, "EMPTY_RETURNS", "至少需要一条收益率记录");
    for (const raw of rows) { if (!isRecord(raw)) continue; const security = await ensureSecurity(context.workspaceId, requiredTicker(raw.ticker)); const date = tradingDate(raw.date); const value = decimal(raw.returnValue, -1, 10, 0); const id = await stableId("ret", `${portfolio.id}:${security.id}:${date}`); await db.prepare("INSERT INTO portfolio_return_series (id,workspace_id,portfolio_id,security_id,trading_date,return_value,as_of,created_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(portfolio_id,security_id,trading_date) DO UPDATE SET return_value=excluded.return_value,as_of=excluded.as_of").bind(id, context.workspaceId, portfolio.id, security.id, date, value, now, now).run(); }
    return { action, imported: rows.length };
  }
  if (action === "scenario.save" || action === "scenario.run") {
    const shocks = parseShocks(input.shocks); const logicalId = optionalString(input.logicalId) ?? await stableId("scl", `${portfolio.id}:${requiredString(input.name, "name", 100)}`); const previous = await db.prepare("SELECT id,version FROM portfolio_scenarios WHERE workspace_id=? AND logical_id=? ORDER BY version DESC LIMIT 1").bind(context.workspaceId, logicalId).first<{ id: string; version: number }>(); const version = (previous?.version ?? 0) + 1; const id = await stableId("scn", `${logicalId}:${version}`);
    await db.prepare("INSERT INTO portfolio_scenarios (id,logical_id,version,workspace_id,portfolio_id,name,description,shocks_json,status,supersedes_id,as_of,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id, logicalId, version, context.workspaceId, portfolio.id, requiredString(input.name, "name", 100), optionalString(input.description, 1000), JSON.stringify(shocks), "active", previous?.id ?? null, validDate(input.asOf) ?? now, now, now).run();
    const state = await loadPositionsAndPolicy(context.workspaceId, portfolio.id); const result = stressPortfolio(state.positions, state.policy, shocks); const hash = await contentHash({ positions: state.positions, policy: state.policy, shocks }); const resultId = await stableId("scr", `${portfolio.id}:${id}:${hash}`);
    await db.prepare("INSERT OR IGNORE INTO portfolio_scenario_results (id,workspace_id,portfolio_id,scenario_id,as_of,input_hash,result_json,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(resultId, context.workspaceId, portfolio.id, id, now, hash, JSON.stringify(result), now).run();
    return { action, id, logicalId, version, result };
  }
  if (action === "risk.refresh") return refreshRisk(context, portfolio.id, now);
  if (action === "condition.acknowledge") { const id = requiredString(input.id, "id"); await db.prepare("UPDATE portfolio_action_conditions SET status='acknowledged',acknowledged_at=?,updated_at=? WHERE id=? AND workspace_id=? AND portfolio_id=?").bind(now, now, id, context.workspaceId, portfolio.id).run(); return { action, id }; }
  throw new HttpError(400, "UNKNOWN_ACTION", `不支持的组合操作：${action}`);
}

async function refreshRisk(context: AuthContext, portfolioId: string, now: string) {
  const db = getD1(); const state = await loadPositionsAndPolicy(context.workspaceId, portfolioId); const risk = calculatePortfolioRisk(state.positions, state.policy); const hash = await contentHash({ positions: state.positions, policy: state.policy }); const snapshotId = await stableId("prs", `${portfolioId}:${hash}`);
  await db.prepare("INSERT OR IGNORE INTO portfolio_risk_snapshots (id,workspace_id,portfolio_id,as_of,input_hash,metrics_json,exposures_json,concentration_json,liquidity_json,warnings_json,model_version,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(snapshotId, context.workspaceId, portfolioId, now, hash, JSON.stringify({ nav: risk.nav, grossExposure: risk.grossExposure, netExposure: risk.netExposure, betaAdjustedNet: risk.betaAdjustedNet }), JSON.stringify(risk.exposures), JSON.stringify({ weights: risk.weights, top5Weight: risk.top5Weight, hhi: risk.hhi, effectivePositions: risk.effectivePositions }), JSON.stringify(risk.liquidity), JSON.stringify(risk.warnings), "portfolio-risk-v1", now).run();
  const returnRows = await db.prepare("SELECT s.ticker,r.trading_date AS tradingDate,r.return_value AS returnValue FROM portfolio_return_series r JOIN securities s ON s.id=r.security_id WHERE r.workspace_id=? AND r.portfolio_id=? ORDER BY r.trading_date DESC LIMIT 10000").bind(context.workspaceId, portfolioId).all<{ ticker: string; tradingDate: string; returnValue: number }>(); const returnSeries = returnRows.results.reduce<Record<string, Record<string, number>>>((result, row) => { (result[row.ticker] ??= {})[row.tradingDate] = row.returnValue; return result; }, {}); const correlation = correlationMatrix(returnSeries, Math.min(20, Math.max(3, Math.floor((state.policy.correlationLookbackDays ?? 60) / 3)))); const correlationHash = await contentHash({ returnSeries, lookbackDays: state.policy.correlationLookbackDays ?? 60, method: "pearson" }); const correlationId = await stableId("pcs", `${portfolioId}:${correlationHash}`); await db.prepare("INSERT OR IGNORE INTO portfolio_correlation_snapshots (id,workspace_id,portfolio_id,as_of,lookback_days,method,matrix_json,coverage,warnings_json,input_hash,created_at) VALUES (?,?,?,?,?,'pearson',?,?,?,?,?)").bind(correlationId, context.workspaceId, portfolioId, now, state.policy.correlationLookbackDays ?? 60, JSON.stringify({ tickers: correlation.tickers, matrix: correlation.matrix }), correlation.coverage, JSON.stringify(correlation.warnings), correlationHash, now).run();
  const theses = await latestThesisSignals(context.workspaceId, state.positions.map((position) => position.ticker)); const scenarioRows = await db.prepare("SELECT result_json AS resultJson FROM portfolio_scenario_results WHERE workspace_id=? AND portfolio_id=? ORDER BY created_at DESC LIMIT 20").bind(context.workspaceId, portfolioId).all<{ resultJson: string }>(); const scenarioLossBps = Math.max(0, ...scenarioRows.results.map((row) => Number(safeObject(row.resultJson).lossBps ?? 0))); const conditions = generateActionConditions(state.positions, state.policy, theses, scenarioLossBps);
  for (const condition of conditions) { const key = await contentHash({ portfolioId, key: condition.key }); const id = await stableId("pac", `${portfolioId}:${key}`); const securityId = condition.ticker ? state.securityIds[condition.ticker] ?? null : null; await db.prepare("INSERT INTO portfolio_action_conditions (id,workspace_id,portfolio_id,security_id,condition_type,trigger_kind,severity,predicate_json,message,status,idempotency_key,triggered_at,as_of,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,'triggered',?,?,?,?,?) ON CONFLICT(portfolio_id,idempotency_key) DO UPDATE SET severity=excluded.severity,predicate_json=excluded.predicate_json,message=excluded.message,status=CASE WHEN portfolio_action_conditions.status='acknowledged' THEN 'acknowledged' ELSE 'triggered' END,as_of=excluded.as_of,updated_at=excluded.updated_at").bind(id, context.workspaceId, portfolioId, securityId, condition.conditionType, condition.triggerKind, condition.severity, JSON.stringify(condition.predicate), condition.message, key, now, now, now, now).run(); }
  return { action: "risk.refresh", id: snapshotId, correlationSnapshotId: correlationId, conditionCount: conditions.length, risk };
}

async function ensurePortfolio(context: AuthContext, requested?: string | null) {
  const db = getD1(); let portfolio = requested ? await db.prepare("SELECT id,name,base_currency AS baseCurrency FROM portfolios WHERE id=? AND workspace_id=?").bind(requested, context.workspaceId).first<{ id: string; name: string; baseCurrency: string }>() : null;
  if (requested && !portfolio) throw new HttpError(404, "PORTFOLIO_NOT_FOUND", "组合不存在");
  if (!portfolio) portfolio = await db.prepare("SELECT id,name,base_currency AS baseCurrency FROM portfolios WHERE workspace_id=? ORDER BY created_at LIMIT 1").bind(context.workspaceId).first<{ id: string; name: string; baseCurrency: string }>();
  if (!portfolio) { const now = new Date().toISOString(); const id = await stableId("por", `${context.workspaceId}:core`); await db.prepare("INSERT OR IGNORE INTO portfolios (id,workspace_id,name,base_currency,created_at,updated_at) VALUES (?,?,?,?,?,?)").bind(id, context.workspaceId, "核心组合", "USD", now, now).run(); portfolio = { id, name: "核心组合", baseCurrency: "USD" }; }
  const now = new Date().toISOString(); const policyId = await stableId("prp", portfolio.id); await db.prepare("INSERT OR IGNORE INTO portfolio_risk_policies (id,workspace_id,portfolio_id,nav,created_at,updated_at) VALUES (?,?,?,0,?,?)").bind(policyId, context.workspaceId, portfolio.id, now, now).run(); return portfolio;
}

async function loadPositionsAndPolicy(workspaceId: string, portfolioId: string) {
  const db = getD1(); const rows = await db.prepare("SELECT pp.id,pp.security_id AS securityId,pp.position_type AS positionType,pp.shares,pp.current_price AS currentPrice,pp.market_value AS marketValue,pp.currency,pp.beta,pp.adv_usd AS advUsd,pp.sector,pp.industry,pp.factor_exposures_json AS factorExposuresJson,pp.event_tags_json AS eventTagsJson,pp.data_status AS dataStatus,s.ticker FROM portfolio_positions pp JOIN securities s ON s.id=pp.security_id WHERE pp.workspace_id=? AND pp.portfolio_id=?").bind(workspaceId, portfolioId).all<JsonRecord>(); const policy = await db.prepare("SELECT nav,max_position_weight AS maxPositionWeight,max_sector_weight AS maxSectorWeight,max_factor_exposure AS maxFactorExposure,max_event_cluster_weight AS maxEventClusterWeight,scenario_loss_budget_bps AS scenarioLossBudgetBps,absolute_loss_cap_bps AS absoluteLossCapBps,exit_participation_rate AS exitParticipationRate FROM portfolio_risk_policies WHERE workspace_id=? AND portfolio_id=?").bind(workspaceId, portfolioId).first<JsonRecord>();
  return { positions: rows.results.map(parsePosition), policy: parsePolicy(policy), securityIds: rows.results.reduce<Record<string, string>>((result, row) => { result[String(row.ticker)] = String(row.securityId); return result; }, {}) };
}

async function latestThesisSignals(workspaceId: string, tickers: string[]) {
  if (!tickers.length) return []; const placeholders = tickers.map(() => "?").join(","); const result = await getD1().prepare(`SELECT s.ticker,t.status,(SELECT f.status FROM thesis_falsifiers f WHERE f.workspace_id=t.workspace_id AND f.thesis_logical_id=t.logical_id AND f.version=(SELECT MAX(x.version) FROM thesis_falsifiers x WHERE x.logical_id=f.logical_id) ORDER BY CASE f.status WHEN 'triggered' THEN 0 WHEN 'warning' THEN 1 ELSE 2 END LIMIT 1) AS falsifierStatus FROM theses t JOIN securities s ON s.id=t.security_id WHERE t.workspace_id=? AND s.ticker IN (${placeholders}) AND t.version=(SELECT MAX(x.version) FROM theses x WHERE x.logical_id=t.logical_id)`).bind(workspaceId, ...tickers).all<{ ticker: string; status: string; falsifierStatus: string | null }>(); return result.results;
}

function parsePosition(row: JsonRecord): PortfolioPosition { return { ...row, ticker: String(row.ticker), positionType: String(row.positionType) as PortfolioPosition["positionType"], shares: Number(row.shares), currentPrice: nullableNumber(row.currentPrice), marketValue: nullableNumber(row.marketValue), beta: nullableNumber(row.beta), advUsd: nullableNumber(row.advUsd), factorExposures: numericObject(safeObject(row.factorExposuresJson)), eventTags: stringArray(safeArray(row.eventTagsJson)), dataStatus: String(row.dataStatus) as PortfolioPosition["dataStatus"] }; }
function parsePolicy(row?: JsonRecord | null): RiskPolicy { return { nav: Number(row?.nav ?? 0), maxPositionWeight: Number(row?.maxPositionWeight ?? .2), maxSectorWeight: Number(row?.maxSectorWeight ?? .4), maxFactorExposure: Number(row?.maxFactorExposure ?? .5), maxEventClusterWeight: Number(row?.maxEventClusterWeight ?? .35), scenarioLossBudgetBps: Number(row?.scenarioLossBudgetBps ?? 1000), absoluteLossCapBps: Number(row?.absoluteLossCapBps ?? 2000), correlationLookbackDays: Number(row?.correlationLookbackDays ?? 60), exitParticipationRate: Number(row?.exitParticipationRate ?? .1) }; }
function parseShocks(value: unknown): Shock[] { if (!Array.isArray(value) || !value.length || value.length > 50) throw new HttpError(400, "INVALID_SHOCKS", "情景需要 1–50 个冲击参数"); return value.map((item) => { if (!isRecord(item)) throw new HttpError(400, "INVALID_SHOCK", "冲击参数格式不正确"); return { dimension: enumValue(item.dimension, ["ticker", "sector", "factor", "currency", "event"] as const, "ticker"), key: requiredString(item.key, "shock.key", 100), percent: decimal(item.percent, -100, 500, 0) }; }); }
async function ensureSecurity(workspaceId: string, ticker: string, issuerName?: string | null) { const now = new Date().toISOString(); const id = await stableId("sec", `${workspaceId}:US:${ticker}`); await getD1().prepare("INSERT INTO securities (id,workspace_id,ticker,exchange,issuer_name,created_at,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(workspace_id,ticker,exchange) DO UPDATE SET issuer_name=COALESCE(excluded.issuer_name,securities.issuer_name),updated_at=excluded.updated_at").bind(id, workspaceId, ticker, "US", issuerName ?? null, now, now).run(); return { id, ticker }; }
function requiredTicker(value: unknown) { const ticker = requiredString(value, "ticker", 10).toUpperCase(); if (!/^[A-Z][A-Z0-9.-]{0,9}$/.test(ticker)) throw new HttpError(400, "INVALID_TICKER", "美股代码格式不正确"); return ticker; }
function requiredString(value: unknown, name: string, max = 200) { if (typeof value !== "string" || !value.trim() || value.trim().length > max) throw new HttpError(400, "INVALID_ARGUMENT", `${name} 格式不正确`); return value.trim(); }
function optionalString(value: unknown, max = 200) { return typeof value === "string" && value.trim() ? value.trim().slice(0, max) : null; }
function enumValue<T extends string>(value: unknown, allowed: readonly T[], fallback: T): T { return typeof value === "string" && allowed.includes(value as T) ? value as T : fallback; }
function decimal(value: unknown, min: number, max: number, fallback: number) { const number = Number(value); return Number.isFinite(number) && number >= min && number <= max ? number : fallback; }
function nullableDecimal(value: unknown) { const number = Number(value); return value !== null && value !== "" && Number.isFinite(number) ? number : null; }
function nullableNumber(value: unknown) { return value == null ? null : Number(value); }
function integer(value: unknown, min: number, max: number, fallback: number) { const number = Number(value); return Number.isInteger(number) && number >= min && number <= max ? number : fallback; }
function ratio(value: unknown, fallback: number) { return decimal(value, 0, 5, fallback); }
function currency(value: unknown) { const result = typeof value === "string" ? value.trim().toUpperCase() : "USD"; return /^[A-Z]{3}$/.test(result) ? result : "USD"; }
function validDate(value: unknown) { return typeof value === "string" && !Number.isNaN(Date.parse(value)) ? new Date(value).toISOString() : null; }
function tradingDate(value: unknown) { if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value) || Number.isNaN(Date.parse(`${value}T00:00:00Z`))) throw new HttpError(400, "INVALID_DATE", "交易日期应为 YYYY-MM-DD"); return value; }
function isRecord(value: unknown): value is JsonRecord { return Boolean(value && typeof value === "object" && !Array.isArray(value)); }
function safeObject(value: unknown): JsonRecord { if (isRecord(value)) return value; if (typeof value === "string") try { const parsed = JSON.parse(value); return isRecord(parsed) ? parsed : {}; } catch { return {}; } return {}; }
function safeArray(value: unknown) { if (Array.isArray(value)) return value; if (typeof value === "string") try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed : []; } catch { return []; } return []; }
function stringArray(value: unknown) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string").map((item) => item.trim()).filter(Boolean).slice(0, 30) : []; }
function numericObject(value: unknown) { const object = isRecord(value) ? value : {}; return Object.fromEntries(Object.entries(object).filter(([, item]) => Number.isFinite(Number(item))).slice(0, 30).map(([key, item]) => [key.slice(0, 80), Number(item)])); }
