import { getD1 } from "../../db";
import type { AuthContext } from "../auth/context";
import { HttpError } from "../auth/context";
import { contentHash, stableId } from "../core/ids";
import { enqueueResearch, MODEL_VERSION, PROMPT_VERSION } from "../research/queue";
import { arbitrateCandidates } from "./analytics";
import type { AgentCandidate, WorkflowDefinition, WorkflowNode } from "./contracts";
import { queueWebhookEvent } from "./webhooks";

type RunRow = { id: string; workspaceId: string; requestedByUserId: string; workflowVersionId: string; securityId: string | null; ticker: string | null; inputJson: string; asOf: string; status: string };
type StepRow = { id: string; nodeKey: string; nodeType: WorkflowNode["type"]; agentRole: string | null; objective: string | null; dependsOnJson: string; status: string; researchJobId: string | null; outputJson: string | null };

export async function startWorkflowRun(context: AuthContext, input: { workflowVersionId?: string | null; ticker?: string | null; question: string; asOf: string; idempotencyKey?: string | null }) {
  const db = getD1(); const now = new Date().toISOString();
  const version = input.workflowVersionId ? await db.prepare("SELECT rwv.id,rwv.definition_json AS definitionJson FROM research_workflow_versions rwv WHERE rwv.id=? AND rwv.workspace_id=? AND rwv.status='published'").bind(input.workflowVersionId, context.workspaceId).first<{ id: string; definitionJson: string }>() : await db.prepare("SELECT rwv.id,rwv.definition_json AS definitionJson FROM research_workflow_versions rwv JOIN research_workflows rw ON rw.id=rwv.workflow_id WHERE rwv.workspace_id=? AND rwv.status='published' ORDER BY CASE rw.slug WHEN 'evidence-first-equity-research' THEN 0 ELSE 1 END,rwv.published_at DESC LIMIT 1").bind(context.workspaceId).first<{ id: string; definitionJson: string }>();
  if (!version) throw new HttpError(404, "WORKFLOW_NOT_FOUND", "没有可运行的已发布 Workflow");
  const definition = JSON.parse(version.definitionJson) as WorkflowDefinition; const ticker = input.ticker?.trim().toUpperCase() || null; let securityId: string | null = null;
  if (ticker) { if (!/^[A-Z][A-Z0-9.-]{0,9}$/.test(ticker)) throw new HttpError(400, "INVALID_TICKER", "美股代码格式不正确"); securityId = await stableId("sec", `${context.workspaceId}:US:${ticker}`); await db.prepare("INSERT OR IGNORE INTO securities (id,workspace_id,ticker,exchange,created_at,updated_at) VALUES (?,?,?,?,?,?)").bind(securityId, context.workspaceId, ticker, "US", now, now).run(); }
  const idempotencyKey = input.idempotencyKey ?? await contentHash({ workspaceId: context.workspaceId, workflowVersionId: version.id, ticker, question: input.question, asOf: input.asOf.slice(0, 10) }); const id = await stableId("wfr", `${context.workspaceId}:${idempotencyKey}`);
  await db.prepare("INSERT OR IGNORE INTO workflow_runs (id,workspace_id,workflow_version_id,security_id,requested_by_user_id,status,input_json,context_json,as_of,idempotency_key,trace_id,created_at,updated_at) VALUES (?,?,?,?,?,'queued',?,'{}',?,?,?, ?,?)").bind(id, context.workspaceId, version.id, securityId, context.userId, JSON.stringify({ ticker, question: input.question }), input.asOf, idempotencyKey, crypto.randomUUID(), now, now).run();
  for (const node of definition.nodes) { const stepId = await stableId("wfs", `${id}:${node.id}`); await db.prepare("INSERT OR IGNORE INTO workflow_step_runs (id,workspace_id,workflow_run_id,node_key,node_type,agent_role,objective,depends_on_json,status,evidence_ids_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?, 'pending','[]',?,?)").bind(stepId, context.workspaceId, id, node.id, node.type, node.role ?? null, node.objective ?? null, JSON.stringify(node.dependsOn ?? []), now, now).run(); }
  await scheduleWorkflowRun(id); return getWorkflowRun(context.workspaceId, id);
}

export async function syncWorkflowRuns(limit = 10) {
  const runs = await getD1().prepare("SELECT wr.id FROM workflow_runs wr WHERE wr.status IN ('queued','running') ORDER BY wr.updated_at LIMIT ?").bind(Math.min(limit, 25)).all<{ id: string }>(); const results = [];
  for (const run of runs.results) { const before = await getD1().prepare("SELECT workspace_id AS workspaceId,status FROM workflow_runs WHERE id=?").bind(run.id).first<{ workspaceId: string; status: string }>(); await syncResearchSteps(run.id); await scheduleWorkflowRun(run.id); const after = await getD1().prepare("SELECT id,status FROM workflow_runs WHERE id=?").bind(run.id).first<{ id: string; status: string }>(); if (before && after && before.status !== after.status && ["awaiting_review","approved","failed"].includes(after.status)) await queueWebhookEvent(before.workspaceId, after.status === "failed" ? "workflow.run.failed" : "workflow.run.completed", { workflowRunId: run.id, status: after.status, requiresHumanReview: after.status === "awaiting_review" }, await stableId("evt", `workflow:${run.id}:${after.status}`)); results.push(after); }
  return results;
}

export async function getWorkflowRun(workspaceId: string, runId: string) {
  const run = await getD1().prepare("SELECT wr.id,wr.workflow_version_id AS workflowVersionId,wr.status,wr.input_json AS inputJson,wr.as_of AS asOf,wr.trace_id AS traceId,wr.created_at AS createdAt,wr.updated_at AS updatedAt,s.ticker,rw.name AS workflowName,rwv.semver AS workflowSemver FROM workflow_runs wr JOIN research_workflow_versions rwv ON rwv.id=wr.workflow_version_id JOIN research_workflows rw ON rw.id=rwv.workflow_id LEFT JOIN securities s ON s.id=wr.security_id WHERE wr.id=? AND wr.workspace_id=?").bind(runId, workspaceId).first<Record<string, unknown>>(); if (!run) return null;
  const steps = await getD1().prepare("SELECT id,node_key AS nodeKey,node_type AS nodeType,agent_role AS agentRole,objective,depends_on_json AS dependsOnJson,status,research_job_id AS researchJobId,output_json AS outputJson,score_json AS scoreJson,error_message AS errorMessage,started_at AS startedAt,completed_at AS completedAt FROM workflow_step_runs WHERE workflow_run_id=? ORDER BY created_at").bind(runId).all<Record<string, unknown>>();
  const decision = await getD1().prepare("SELECT selected_candidate_id AS selectedCandidateId,candidate_scores_json AS candidateScoresJson,explanation_json AS explanationJson,dissent_json AS dissentJson,confidence,as_of AS asOf FROM arbitration_decisions WHERE workflow_run_id=? ORDER BY created_at DESC LIMIT 1").bind(runId).first<Record<string, unknown>>();
  return { ...run, input: parse(run.inputJson), inputJson: undefined, steps: steps.results.map((step) => ({ ...step, dependsOn: parse(step.dependsOnJson), output: parse(step.outputJson), score: parse(step.scoreJson), dependsOnJson: undefined, outputJson: undefined, scoreJson: undefined })), arbitration: decision ? { ...decision, candidateScores: parse(decision.candidateScoresJson), explanation: parse(decision.explanationJson), dissent: parse(decision.dissentJson), candidateScoresJson: undefined, explanationJson: undefined, dissentJson: undefined } : null };
}

async function syncResearchSteps(runId: string) {
  const db = getD1(); const now = new Date().toISOString(); const steps = await db.prepare("SELECT ws.id,ws.research_job_id AS researchJobId,rj.status,rj.snapshot_json AS snapshotJson,rj.error_message AS errorMessage,rj.model_version AS modelVersion,rj.prompt_version AS promptVersion FROM workflow_step_runs ws JOIN research_jobs rj ON rj.id=ws.research_job_id WHERE ws.workflow_run_id=? AND ws.status IN ('queued','running')").bind(runId).all<{ id: string; researchJobId: string; status: string; snapshotJson: string | null; errorMessage: string | null; modelVersion: string; promptVersion: string }>();
  for (const step of steps.results) { if (step.status === "succeeded") await db.prepare("UPDATE workflow_step_runs SET status='succeeded',output_json=?,model_version=?,prompt_version=?,completed_at=?,updated_at=? WHERE id=?").bind(step.snapshotJson, step.modelVersion, step.promptVersion, now, now, step.id).run(); else if (["failed", "cancelled"].includes(step.status)) await db.prepare("UPDATE workflow_step_runs SET status='failed',error_message=?,completed_at=?,updated_at=? WHERE id=?").bind(step.errorMessage ?? step.status, now, now, step.id).run(); else await db.prepare("UPDATE workflow_step_runs SET status=?,updated_at=? WHERE id=?").bind(step.status, now, step.id).run(); }
}

async function scheduleWorkflowRun(runId: string) {
  const db = getD1(); const run = await db.prepare("SELECT wr.id,wr.workspace_id AS workspaceId,wr.requested_by_user_id AS requestedByUserId,wr.workflow_version_id AS workflowVersionId,wr.security_id AS securityId,wr.input_json AS inputJson,wr.as_of AS asOf,wr.status,s.ticker FROM workflow_runs wr LEFT JOIN securities s ON s.id=wr.security_id WHERE wr.id=?").bind(runId).first<RunRow>(); if (!run || !["queued", "running"].includes(run.status)) return;
  const version = await db.prepare("SELECT definition_json AS definitionJson FROM research_workflow_versions WHERE id=?").bind(run.workflowVersionId).first<{ definitionJson: string }>(); if (!version) return; const definition = JSON.parse(version.definitionJson) as WorkflowDefinition;
  const steps = await db.prepare("SELECT id,node_key AS nodeKey,node_type AS nodeType,agent_role AS agentRole,objective,depends_on_json AS dependsOnJson,status,research_job_id AS researchJobId,output_json AS outputJson FROM workflow_step_runs WHERE workflow_run_id=? ORDER BY created_at").bind(runId).all<StepRow>(); const byKey = new Map(steps.results.map((step) => [step.nodeKey, step])); const now = new Date().toISOString();
  if (steps.results.some((step) => step.status === "failed") && definition.failurePolicy !== "continue_independent") { await db.prepare("UPDATE workflow_runs SET status='failed',error_message='Workflow step failed',completed_at=?,updated_at=? WHERE id=?").bind(now, now, runId).run(); return; }
  for (const node of definition.nodes) {
    const step = byKey.get(node.id); if (!step || step.status !== "pending") continue; const dependencies = node.dependsOn ?? []; if (!dependencies.every((key) => byKey.get(key)?.status === "succeeded")) continue;
    if (node.type === "agent") { const input = parse(run.inputJson) as { question?: string; ticker?: string }; const context: AuthContext = { workspaceId: run.workspaceId, userId: run.requestedByUserId, email: "workflow@alphalens.local", role: "editor" }; const skill = node.skillSlug ? await installedSkill(run.workspaceId, node.skillSlug) : null; const job = await enqueueResearch(context, { ticker: run.ticker ?? input.ticker ?? "SPY", question: `[Agent role: ${node.role}] ${node.objective}.${skill ? ` Installed skill ${node.skillSlug}: ${skill}` : ""} Research request: ${input.question ?? "Evidence-first public equity research"}`.slice(0, 1200), asOf: run.asOf, idempotencyKey: await contentHash({ runId, node: node.id, skill: node.skillSlug }) }); await db.prepare("UPDATE workflow_step_runs SET status='queued',research_job_id=?,started_at=?,model_version=?,prompt_version=?,updated_at=? WHERE id=?").bind(String(job?.id), now, MODEL_VERSION, PROMPT_VERSION, now, step.id).run(); }
    if (node.type === "arbitration") await executeArbitration(run, step, dependencies.map((key) => byKey.get(key)!).filter(Boolean), definition, now);
    if (node.type === "approval") await db.prepare("UPDATE workflow_step_runs SET status='waiting_approval',updated_at=? WHERE id=?").bind(now, step.id).run();
  }
  const refreshed = await db.prepare("SELECT status,node_type AS nodeType FROM workflow_step_runs WHERE workflow_run_id=?").bind(runId).all<{ status: string; nodeType: string }>(); const hasActive = refreshed.results.some((step) => ["pending", "queued", "running"].includes(step.status)); const awaiting = refreshed.results.some((step) => step.status === "waiting_approval") || refreshed.results.some((step) => step.nodeType === "arbitration" && step.status === "succeeded"); await db.prepare("UPDATE workflow_runs SET status=?,started_at=COALESCE(started_at,?),completed_at=?,updated_at=? WHERE id=?").bind(hasActive ? "running" : awaiting ? "awaiting_review" : "approved", now, hasActive ? null : now, now, runId).run();
}

async function executeArbitration(run: RunRow, step: StepRow, dependencies: StepRow[], definition: WorkflowDefinition, now: string) {
  const candidates: AgentCandidate[] = dependencies.map((candidate) => { const output = parse(candidate.outputJson) as { sources?: Array<{ provider?: string; freshness?: string }>; warnings?: unknown[] }; const sources = output?.sources ?? []; return { id: candidate.id, role: candidate.agentRole ?? candidate.nodeKey, output, evidenceCount: sources.length, primarySourceCount: sources.filter((source) => ["sec-edgar", "issuer-ir"].includes(source.provider ?? "")).length, contradictionsAddressed: candidate.agentRole?.includes("challenger") ? 2 : 1, staleSourceCount: sources.filter((source) => source.freshness === "stale").length, reasoningSignals: Math.min(5, 2 + sources.length) }; }); const result = arbitrateCandidates(candidates, definition.arbitrationRubric); const decisionId = await stableId("arb", `${run.id}:${step.id}`);
  await getD1().batch([getD1().prepare("INSERT OR REPLACE INTO arbitration_decisions (id,workspace_id,workflow_run_id,step_run_id,rubric_version,selected_candidate_id,candidate_scores_json,explanation_json,dissent_json,confidence,as_of,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(decisionId, run.workspaceId, run.id, step.id, "arbitration-v1", result.winner?.id ?? null, JSON.stringify(result.scores), JSON.stringify(result.explanation), JSON.stringify(result.dissent), result.confidence, run.asOf, now), getD1().prepare("UPDATE workflow_step_runs SET status='succeeded',output_json=?,score_json=?,completed_at=?,updated_at=? WHERE id=?").bind(JSON.stringify({ selectedCandidateId: result.winner?.id, explanation: result.explanation, dissent: result.dissent }), JSON.stringify(result.scores), now, now, step.id)]);
}

function parse(value: unknown): unknown { if (typeof value !== "string") return value ?? null; try { return JSON.parse(value); } catch { return null; } }
async function installedSkill(workspaceId: string, slug: string) { const row = await getD1().prepare("SELECT rsv.instructions FROM skill_installations si JOIN research_skill_versions rsv ON rsv.id=si.skill_version_id JOIN research_skills rs ON rs.id=rsv.skill_id WHERE si.workspace_id=? AND si.enabled=1 AND rs.slug=? AND rsv.status='published' ORDER BY rsv.version DESC LIMIT 1").bind(workspaceId, slug).first<{ instructions: string }>(); return row?.instructions ?? null; }
