import { getD1 } from "../../db";
import type { AuthContext } from "../auth/context";
import { HttpError } from "../auth/context";
import { contentHash, stableId } from "../core/ids";
import { encryptConnectorSecret } from "../workbench/connectors";
import { explainQuality, routeProviders, validateSkillManifest, validateWorkflow } from "./analytics";
import type { ProviderRequest, ProviderRoute, ResearchSkillManifest, WorkflowDefinition } from "./contracts";
import { getWorkflowRun, startWorkflowRun } from "./orchestrator";
import { queueWebhookEvent, validateWebhookUrl } from "./webhooks";

type JsonRecord = Record<string, unknown>;

export async function getPlatform(context: AuthContext, runId?: string | null) {
  await ensurePlatformDefaults(context); const db = getD1();
  const workflows = await db.prepare("SELECT rw.id,rw.slug,rw.name,rw.description,rw.visibility,rwv.id AS versionId,rwv.semver,rwv.status,rwv.definition_json AS definitionJson,rwv.published_at AS publishedAt FROM research_workflows rw LEFT JOIN research_workflow_versions rwv ON rwv.id=(SELECT x.id FROM research_workflow_versions x WHERE x.workflow_id=rw.id ORDER BY x.version DESC LIMIT 1) WHERE rw.workspace_id=? ORDER BY rw.updated_at DESC").bind(context.workspaceId).all<JsonRecord>();
  const kpiModels = await db.prepare("SELECT km.id,km.slug,km.name,km.sector,km.industry,kmv.semver,kmv.status,kmv.metrics_json AS metricsJson FROM kpi_models km LEFT JOIN kpi_model_versions kmv ON kmv.id=(SELECT x.id FROM kpi_model_versions x WHERE x.kpi_model_id=km.id ORDER BY x.version DESC LIMIT 1) WHERE km.workspace_id=? ORDER BY km.sector,km.name").bind(context.workspaceId).all<JsonRecord>();
  const routes = await db.prepare("SELECT pr.id,pr.category,pr.provider,pr.capability,pr.priority,pr.license_scope AS licenseScope,pr.allowed_use AS allowedUse,pr.max_latency_ms AS maxLatencyMs,pr.max_cost_usd AS maxCostUsd,pr.freshness_seconds AS freshnessSeconds,pr.enabled,ps.status AS health,ps.latency_ms AS latencyMs FROM provider_routes pr LEFT JOIN provider_state ps ON ps.provider=pr.provider WHERE pr.workspace_id=? ORDER BY pr.category,pr.priority").bind(context.workspaceId).all<JsonRecord>();
  const skills = await db.prepare("SELECT rs.id,rs.slug,rs.name,rs.description,rs.category,rs.visibility,rsv.id AS versionId,rsv.semver,rsv.status,rsv.permissions_json AS permissionsJson,rsv.validation_json AS validationJson,CASE WHEN si.id IS NULL THEN 0 ELSE 1 END AS installed FROM research_skills rs JOIN research_skill_versions rsv ON rsv.id=(SELECT x.id FROM research_skill_versions x WHERE x.skill_id=rs.id ORDER BY x.version DESC LIMIT 1) LEFT JOIN skill_installations si ON si.skill_version_id=rsv.id AND si.workspace_id=? WHERE rs.workspace_id=? OR rs.visibility='marketplace' ORDER BY rs.category,rs.name").bind(context.workspaceId, context.workspaceId).all<JsonRecord>();
  const runs = await db.prepare("SELECT wr.id,wr.status,wr.as_of AS asOf,wr.created_at AS createdAt,s.ticker,rw.name AS workflowName,rwv.semver,(SELECT COUNT(*) FROM workflow_step_runs ws WHERE ws.workflow_run_id=wr.id) AS stepCount,(SELECT COUNT(*) FROM workflow_step_runs ws WHERE ws.workflow_run_id=wr.id AND ws.status='succeeded') AS completedSteps FROM workflow_runs wr JOIN research_workflow_versions rwv ON rwv.id=wr.workflow_version_id JOIN research_workflows rw ON rw.id=rwv.workflow_id LEFT JOIN securities s ON s.id=wr.security_id WHERE wr.workspace_id=? ORDER BY wr.created_at DESC LIMIT 30").bind(context.workspaceId).all<JsonRecord>();
  const artifacts = await db.prepare("SELECT ra.id,ra.logical_id AS logicalId,ra.artifact_type AS artifactType,ra.title,rav.id AS versionId,rav.version,rav.status,rav.as_of AS asOf,rav.published_at AS publishedAt,s.ticker FROM research_artifacts ra JOIN research_artifact_versions rav ON rav.id=(SELECT x.id FROM research_artifact_versions x WHERE x.artifact_id=ra.id ORDER BY x.version DESC LIMIT 1) LEFT JOIN securities s ON s.id=ra.security_id WHERE ra.workspace_id=? ORDER BY rav.updated_at DESC LIMIT 50").bind(context.workspaceId).all<JsonRecord>();
  const approvals = await db.prepare("SELECT ar.id,ar.artifact_version_id AS artifactVersionId,ar.required_role AS requiredRole,ar.status,ar.decision_note AS decisionNote,ar.created_at AS createdAt,ra.title FROM approval_requests ar JOIN research_artifact_versions rav ON rav.id=ar.artifact_version_id JOIN research_artifacts ra ON ra.id=rav.artifact_id WHERE ar.workspace_id=? ORDER BY ar.created_at DESC LIMIT 50").bind(context.workspaceId).all<JsonRecord>();
  const comments = await db.prepare("SELECT tc.id,tc.artifact_version_id AS artifactVersionId,tc.parent_id AS parentId,tc.anchor_json AS anchorJson,tc.body,tc.status,tc.created_at AS createdAt,tc.resolved_at AS resolvedAt,u.display_name AS authorName FROM team_comments tc JOIN users u ON u.id=tc.author_user_id WHERE tc.workspace_id=? ORDER BY tc.created_at DESC LIMIT 100").bind(context.workspaceId).all<JsonRecord>();
  const evaluations = await db.prepare("SELECT er.id,er.status,er.scores_json AS scoresJson,er.explanations_json AS explanationsJson,er.sample_count AS sampleCount,er.passed_count AS passedCount,er.as_of AS asOf,bs.name AS suiteName FROM evaluation_runs er JOIN benchmark_suites bs ON bs.id=er.suite_id WHERE er.workspace_id=? ORDER BY er.created_at DESC LIMIT 30").bind(context.workspaceId).all<JsonRecord>();
  const apiClients = await db.prepare("SELECT id,name,key_prefix AS keyPrefix,scopes_json AS scopesJson,enabled,expires_at AS expiresAt,last_used_at AS lastUsedAt,revoked_at AS revokedAt,created_at AS createdAt FROM api_clients WHERE workspace_id=? ORDER BY created_at DESC").bind(context.workspaceId).all<JsonRecord>();
  const webhooks = await db.prepare("SELECT id,name,endpoint_url AS endpointUrl,event_types_json AS eventTypesJson,enabled,verification_status AS verificationStatus,consecutive_failures AS consecutiveFailures,last_delivery_at AS lastDeliveryAt,created_at AS createdAt FROM webhook_subscriptions WHERE workspace_id=? ORDER BY created_at DESC").bind(context.workspaceId).all<JsonRecord>();
  const benchmarkSuites = await db.prepare("SELECT bs.id,bs.slug,bs.name,bs.description,bs.version,(SELECT COUNT(*) FROM benchmark_cases bc WHERE bc.suite_id=bs.id) AS caseCount FROM benchmark_suites bs WHERE bs.workspace_id=? ORDER BY bs.updated_at DESC").bind(context.workspaceId).all<JsonRecord>();
  return { workflows: workflows.results.map(parseColumns), kpiModels: kpiModels.results.map(parseColumns), providerRoutes: routes.results, skills: skills.results.map(parseColumns), runs: runs.results, selectedRun: runId ? await getWorkflowRun(context.workspaceId, runId) : runs.results[0] ? await getWorkflowRun(context.workspaceId, String(runs.results[0].id)) : null, artifacts: artifacts.results, comments: comments.results.map(parseColumns), approvals: approvals.results, evaluations: evaluations.results.map(parseColumns), benchmarkSuites: benchmarkSuites.results, apiClients: apiClients.results.map(parseColumns), webhooks: webhooks.results.map(parseColumns), asOf: new Date().toISOString(), platformVersion: "0.5.0-beta" };
}

export async function mutatePlatform(context: AuthContext, input: JsonRecord) {
  await ensurePlatformDefaults(context); const action = requiredString(input.action, "action"); const db = getD1(); const now = new Date().toISOString();
  if (["api_client.create", "api_client.revoke", "webhook.save", "webhook.disable"].includes(action) && context.role !== "owner") throw new HttpError(403, "OWNER_REQUIRED", "API 与 Webhook 凭据仅 Workspace Owner 可管理");
  if (action === "workflow.save") { const name = requiredString(input.name, "name", 100); const slug = slugValue(input.slug ?? name); const definition = requireObject(input.definition) as unknown as WorkflowDefinition; const validation = validateWorkflow(definition); if (!validation.valid) throw new HttpError(400, "INVALID_WORKFLOW", validation.errors.join("；")); const workflowId = optionalString(input.workflowId) ?? await stableId("rwf", `${context.workspaceId}:${slug}`); await db.prepare("INSERT INTO research_workflows (id,workspace_id,slug,name,description,owner_user_id,visibility,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(workspace_id,slug) DO UPDATE SET name=excluded.name,description=excluded.description,visibility=excluded.visibility,updated_at=excluded.updated_at").bind(workflowId, context.workspaceId, slug, name, optionalString(input.description, 1000), context.userId, enumValue(input.visibility, ["private","workspace","marketplace"] as const, "workspace"), now, now).run(); const resolved = await db.prepare("SELECT id FROM research_workflows WHERE workspace_id=? AND slug=?").bind(context.workspaceId, slug).first<{ id: string }>(); const id = resolved!.id; const previous = await db.prepare("SELECT id,logical_id AS logicalId,version FROM research_workflow_versions WHERE workflow_id=? ORDER BY version DESC LIMIT 1").bind(id).first<{ id: string; logicalId: string; version: number }>(); const logicalId = previous?.logicalId ?? await stableId("rwl", id); const version = (previous?.version ?? 0) + 1; const versionId = await stableId("rwv", `${logicalId}:${version}`); const checksum = await contentHash(definition); const status = enumValue(input.status, ["draft","published"] as const, "draft"); await db.prepare("INSERT INTO research_workflow_versions (id,logical_id,version,workflow_id,workspace_id,semver,definition_json,input_schema_json,output_schema_json,status,checksum,supersedes_id,published_at,created_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(versionId, logicalId, version, id, context.workspaceId, semver(input.semver, version), JSON.stringify(definition), JSON.stringify(objectOrEmpty(input.inputSchema)), JSON.stringify(objectOrEmpty(input.outputSchema)), status, checksum, previous?.id ?? null, status === "published" ? now : null, context.userId, now, now).run(); return { action, id, versionId, validation }; }
  if (action === "kpi.save") { const name = requiredString(input.name, "name", 100); const slug = slugValue(input.slug ?? name); const metrics = requireArray(input.metrics, "metrics", 100); validateMetrics(metrics); const modelId = optionalString(input.modelId) ?? await stableId("kpm", `${context.workspaceId}:${slug}`); await db.prepare("INSERT INTO kpi_models (id,workspace_id,slug,name,sector,industry,owner_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(workspace_id,slug) DO UPDATE SET name=excluded.name,sector=excluded.sector,industry=excluded.industry,updated_at=excluded.updated_at").bind(modelId, context.workspaceId, slug, name, requiredString(input.sector, "sector", 100), optionalString(input.industry, 120), context.userId, now, now).run(); const model = await db.prepare("SELECT id FROM kpi_models WHERE workspace_id=? AND slug=?").bind(context.workspaceId, slug).first<{ id: string }>(); const previous = await db.prepare("SELECT id,logical_id AS logicalId,version FROM kpi_model_versions WHERE kpi_model_id=? ORDER BY version DESC LIMIT 1").bind(model!.id).first<{ id: string; logicalId: string; version: number }>(); const logicalId = previous?.logicalId ?? await stableId("kpl", model!.id); const version = (previous?.version ?? 0) + 1; const id = await stableId("kpv", `${logicalId}:${version}`); const status = enumValue(input.status, ["draft","published"] as const, "published"); await db.prepare("INSERT INTO kpi_model_versions (id,logical_id,version,kpi_model_id,workspace_id,semver,metrics_json,validation_rules_json,status,checksum,supersedes_id,published_at,created_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id, logicalId, version, model!.id, context.workspaceId, semver(input.semver, version), JSON.stringify(metrics), JSON.stringify(arrayOrEmpty(input.validationRules)), status, await contentHash(metrics), previous?.id ?? null, status === "published" ? now : null, context.userId, now, now).run(); return { action, id, modelId: model!.id, version }; }
  if (action === "provider.route.save") { const provider = slugValue(input.provider); const capability = slugValue(input.capability); const id = await stableId("pvr", `${context.workspaceId}:${capability}:${provider}`); await db.prepare("INSERT INTO provider_routes (id,workspace_id,category,provider,capability,priority,license_scope,allowed_use,max_latency_ms,max_cost_usd,freshness_seconds,enabled,config_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(workspace_id,capability,provider) DO UPDATE SET category=excluded.category,priority=excluded.priority,license_scope=excluded.license_scope,allowed_use=excluded.allowed_use,max_latency_ms=excluded.max_latency_ms,max_cost_usd=excluded.max_cost_usd,freshness_seconds=excluded.freshness_seconds,enabled=excluded.enabled,config_json=excluded.config_json,updated_at=excluded.updated_at").bind(id, context.workspaceId, requiredString(input.category, "category", 100), provider, capability, integer(input.priority, 1, 1000, 100), requiredString(input.licenseScope, "licenseScope", 200), requiredString(input.allowedUse, "allowedUse", 100), nullableInteger(input.maxLatencyMs), nullableDecimal(input.maxCostUsd), integer(input.freshnessSeconds, 1, 31_536_000, 3600), booleanValue(input.enabled, true) ? 1 : 0, JSON.stringify(objectOrEmpty(input.config)), now, now).run(); return { action, id }; }
  if (action === "provider.route.preview") { const routes = await loadProviderRoutes(context.workspaceId); const request = requireObject(input.request) as unknown as ProviderRequest; return { action, ...routeProviders(routes, request) }; }
  if (action === "skill.publish") { const manifest = requireObject(input.manifest) as unknown as ResearchSkillManifest; const validation = validateSkillManifest(manifest); if (!validation.valid) throw new HttpError(400, "INVALID_SKILL", validation.errors.join("；")); const skillId = await stableId("rsk", `${context.workspaceId}:${manifest.name}`); await db.prepare("INSERT INTO research_skills (id,workspace_id,slug,name,description,publisher_user_id,visibility,category,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(workspace_id,slug) DO UPDATE SET name=excluded.name,description=excluded.description,visibility=excluded.visibility,category=excluded.category,updated_at=excluded.updated_at").bind(skillId, context.workspaceId, manifest.name, requiredString(input.displayName ?? manifest.name, "displayName", 100), manifest.description, context.userId, enumValue(input.visibility, ["private","workspace","marketplace"] as const, "workspace"), manifest.category, now, now).run(); const previous = await db.prepare("SELECT id,logical_id AS logicalId,version FROM research_skill_versions WHERE skill_id=? ORDER BY version DESC LIMIT 1").bind(skillId).first<{ id: string; logicalId: string; version: number }>(); const logicalId = previous?.logicalId ?? await stableId("rsl", skillId); const version = (previous?.version ?? 0) + 1; const id = await stableId("rsv", `${logicalId}:${version}`); await db.prepare("INSERT INTO research_skill_versions (id,logical_id,version,skill_id,workspace_id,semver,manifest_json,instructions,input_schema_json,output_schema_json,permissions_json,status,checksum,supersedes_id,published_at,validation_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id, logicalId, version, skillId, context.workspaceId, manifest.version, JSON.stringify(manifest), requiredString(input.instructions, "instructions", 20_000), JSON.stringify(objectOrEmpty(input.inputSchema)), JSON.stringify(objectOrEmpty(input.outputSchema)), JSON.stringify(manifest.permissions), "published", await contentHash({ manifest, instructions: input.instructions }), previous?.id ?? null, now, JSON.stringify(validation), now, now).run(); return { action, id, skillId, validation }; }
  if (action === "skill.install") { const skillVersionId = requiredString(input.skillVersionId, "skillVersionId"); const version = await db.prepare("SELECT id,permissions_json AS permissionsJson,status FROM research_skill_versions WHERE id=? AND status='published'").bind(skillVersionId).first<{ id: string; permissionsJson: string; status: string }>(); if (!version) throw new HttpError(404, "SKILL_NOT_FOUND", "Skill 版本不存在或不可安装"); const granted = objectOrEmpty(input.grantedPermissions); if (!permissionSubset(granted, parse(version.permissionsJson))) throw new HttpError(400, "EXCESSIVE_PERMISSION", "授权范围不能超过 Skill 声明权限"); const id = await stableId("rsi", `${context.workspaceId}:${skillVersionId}`); await db.prepare("INSERT INTO skill_installations (id,workspace_id,skill_version_id,installed_by_user_id,enabled,granted_permissions_json,installed_at,updated_at) VALUES (?,?,?,?,1,?,?,?) ON CONFLICT(workspace_id,skill_version_id) DO UPDATE SET enabled=1,granted_permissions_json=excluded.granted_permissions_json,updated_at=excluded.updated_at").bind(id, context.workspaceId, skillVersionId, context.userId, JSON.stringify(granted), now, now).run(); return { action, id }; }
  if (action === "workflow.run") return startWorkflowRun(context, { workflowVersionId: optionalString(input.workflowVersionId), ticker: optionalString(input.ticker), question: requiredString(input.question, "question", 1200), asOf: validDate(input.asOf) ?? now, idempotencyKey: optionalString(input.idempotencyKey) });
  if (action === "artifact.save") { const runId = optionalString(input.workflowRunId); const securityId = optionalString(input.securityId); if (runId && !await db.prepare("SELECT id FROM workflow_runs WHERE id=? AND workspace_id=?").bind(runId, context.workspaceId).first()) throw new HttpError(404, "RUN_NOT_FOUND", "Workflow Run 不属于当前 Workspace"); if (securityId && !await db.prepare("SELECT id FROM securities WHERE id=? AND workspace_id=?").bind(securityId, context.workspaceId).first()) throw new HttpError(404, "SECURITY_NOT_FOUND", "Security 不属于当前 Workspace"); const logicalId = optionalString(input.logicalId) ?? await stableId("ral", `${context.workspaceId}:${runId ?? crypto.randomUUID()}:${requiredString(input.title, "title", 200)}`); let artifact = await db.prepare("SELECT id FROM research_artifacts WHERE workspace_id=? AND logical_id=?").bind(context.workspaceId, logicalId).first<{ id: string }>(); if (!artifact) { const id = await stableId("rat", `${context.workspaceId}:${logicalId}`); await db.prepare("INSERT INTO research_artifacts (id,workspace_id,workflow_run_id,security_id,logical_id,artifact_type,title,owner_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(id, context.workspaceId, runId, securityId, logicalId, enumValue(input.artifactType, ["report","memo","model","dataset","decision_card"] as const, "report"), requiredString(input.title, "title", 200), context.userId, now, now).run(); artifact = { id }; } const previous = await db.prepare("SELECT id,version FROM research_artifact_versions WHERE artifact_id=? ORDER BY version DESC LIMIT 1").bind(artifact.id).first<{ id: string; version: number }>(); const version = (previous?.version ?? 0) + 1; const id = await stableId("rav", `${artifact.id}:${version}`); const content = input.content ?? {}; await db.prepare("INSERT INTO research_artifact_versions (id,artifact_id,workspace_id,version,content_json,source_snapshot_json,checksum,status,as_of,created_by_user_id,supersedes_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id, artifact.id, context.workspaceId, version, JSON.stringify(content), JSON.stringify(objectOrEmpty(input.sourceSnapshot)), await contentHash(content), "draft", validDate(input.asOf) ?? now, context.userId, previous?.id ?? null, now, now).run(); return { action, id, artifactId: artifact.id, logicalId, version }; }
  if (action === "comment.add") { const artifactVersionId = requiredString(input.artifactVersionId, "artifactVersionId"); await assertArtifactVersion(context.workspaceId, artifactVersionId); const id = crypto.randomUUID(); await db.prepare("INSERT INTO team_comments (id,workspace_id,artifact_version_id,author_user_id,parent_id,anchor_json,body,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'open',?,?)").bind(id, context.workspaceId, artifactVersionId, context.userId, optionalString(input.parentId), JSON.stringify(objectOrEmpty(input.anchor)), requiredString(input.body, "body", 4000), now, now).run(); return { action, id }; }
  if (action === "comment.resolve") { const id = requiredString(input.id, "id"); await db.prepare("UPDATE team_comments SET status='resolved',resolved_by_user_id=?,resolved_at=?,updated_at=? WHERE id=? AND workspace_id=?").bind(context.userId, now, now, id, context.workspaceId).run(); return { action, id }; }
  if (action === "approval.request") { const artifactVersionId = requiredString(input.artifactVersionId, "artifactVersionId"); await assertArtifactVersion(context.workspaceId, artifactVersionId); const id = crypto.randomUUID(); await db.batch([db.prepare("INSERT INTO approval_requests (id,workspace_id,artifact_version_id,requested_by_user_id,reviewer_user_id,required_role,status,created_at,updated_at) VALUES (?,?,?,?,?,?,'pending',?,?)").bind(id, context.workspaceId, artifactVersionId, context.userId, optionalString(input.reviewerUserId), enumValue(input.requiredRole, ["owner","editor"] as const, "editor"), now, now), db.prepare("UPDATE research_artifact_versions SET status='in_review',updated_at=? WHERE id=? AND workspace_id=?").bind(now, artifactVersionId, context.workspaceId)]); return { action, id }; }
  if (action === "approval.decide") { const id = requiredString(input.id, "id"); const decision = enumValue(input.decision, ["approved","changes_requested","rejected"] as const, "changes_requested"); const approval = await db.prepare("SELECT ar.artifact_version_id AS artifactVersionId,ar.required_role AS requiredRole,wm.role FROM approval_requests ar JOIN workspace_members wm ON wm.workspace_id=ar.workspace_id AND wm.user_id=? WHERE ar.id=? AND ar.workspace_id=? AND ar.status='pending'").bind(context.userId, id, context.workspaceId).first<{ artifactVersionId: string; requiredRole: string; role: string }>(); if (!approval || roleRank(approval.role) < roleRank(approval.requiredRole)) throw new HttpError(403, "APPROVAL_FORBIDDEN", "没有所需审批权限"); await db.batch([db.prepare("UPDATE approval_requests SET status=?,decision_note=?,decided_by_user_id=?,decided_at=?,updated_at=? WHERE id=?").bind(decision, optionalString(input.note, 2000), context.userId, now, now, id), db.prepare("UPDATE research_artifact_versions SET status=?,updated_at=? WHERE id=?").bind(decision === "approved" ? "approved" : decision === "rejected" ? "rejected" : "draft", now, approval.artifactVersionId)]); return { action, id, artifactVersionId: approval.artifactVersionId, decision }; }
  if (action === "artifact.publish") { const id = requiredString(input.artifactVersionId, "artifactVersionId"); const artifact = await db.prepare("SELECT rav.id,rav.status,rav.artifact_id AS artifactId,ra.title,ra.logical_id AS logicalId FROM research_artifact_versions rav JOIN research_artifacts ra ON ra.id=rav.artifact_id WHERE rav.id=? AND rav.workspace_id=?").bind(id, context.workspaceId).first<{ id: string; status: string; artifactId: string; title: string; logicalId: string }>(); if (!artifact || artifact.status !== "approved") throw new HttpError(409, "NOT_APPROVED", "研究版本必须审批通过后才能发布"); const openComments = await db.prepare("SELECT COUNT(*) AS count FROM team_comments WHERE artifact_version_id=? AND status='open'").bind(id).first<{ count: number }>(); if (Number(openComments?.count)) throw new HttpError(409, "OPEN_COMMENTS", "仍有未解决评论，不能发布"); await db.batch([db.prepare("UPDATE research_artifact_versions SET status='superseded',updated_at=? WHERE artifact_id=? AND status='published'").bind(now, artifact.artifactId), db.prepare("UPDATE research_artifact_versions SET status='published',published_at=?,updated_at=? WHERE id=?").bind(now, now, id)]); const eventId = await stableId("evt", `research.version.published:${id}`); const queued = await queueWebhookEvent(context.workspaceId, "research.version.published", { artifactVersionId: id, artifactId: artifact.artifactId, logicalId: artifact.logicalId, title: artifact.title, publishedAt: now }, eventId); return { action, id, queuedWebhooks: queued }; }
  if (action === "benchmark.evaluate") { const suiteId = requiredString(input.suiteId, "suiteId"); const suite = await db.prepare("SELECT id FROM benchmark_suites WHERE id=? AND workspace_id=?").bind(suiteId, context.workspaceId).first(); if (!suite) throw new HttpError(404, "SUITE_NOT_FOUND", "Benchmark Suite 不存在"); const metrics = requireObject(input.metrics) as { citations?: number; primaryCitations?: number; contradictions?: number; staleSources?: number; unsupportedClaims?: number; leakageViolations?: number }; const result = explainQuality({ citations: integer(metrics.citations, 0, 10000, 0), primaryCitations: integer(metrics.primaryCitations, 0, 10000, 0), contradictions: integer(metrics.contradictions, 0, 10000, 0), staleSources: integer(metrics.staleSources, 0, 10000, 0), unsupportedClaims: integer(metrics.unsupportedClaims, 0, 10000, 0), leakageViolations: integer(metrics.leakageViolations, 0, 10000, 0) }); const id = crypto.randomUUID(); await db.prepare("INSERT INTO evaluation_runs (id,workspace_id,suite_id,workflow_version_id,skill_version_id,status,scores_json,explanations_json,sample_count,passed_count,model_version,prompt_version,as_of,started_at,completed_at,created_at,updated_at) VALUES (?,?,?,?,?,'succeeded',?,?,?,?,?,?,?,?,?,?,?)").bind(id, context.workspaceId, suiteId, optionalString(input.workflowVersionId), optionalString(input.skillVersionId), JSON.stringify({ overall: result.score, dimensions: result.dimensions }), JSON.stringify(result.failures), 1, result.passed ? 1 : 0, optionalString(input.modelVersion) ?? "platform-eval-v1", optionalString(input.promptVersion) ?? "quality-rubric-v1", validDate(input.asOf) ?? now, now, now, now, now).run(); return { action, id, result }; }
  if (action === "api_client.create") { const name = requiredString(input.name, "name", 100); const scopes = stringArray(input.scopes); if (!scopes.length || scopes.some((scope) => !["research:write","research:read","artifacts:read","webhooks:write"].includes(scope))) throw new HttpError(400, "INVALID_SCOPES", "API scopes 不合法"); const secret = `alp_${randomToken()}`; const id = crypto.randomUUID(); await db.prepare("INSERT INTO api_clients (id,workspace_id,name,key_prefix,secret_hash,scopes_json,created_by_user_id,enabled,expires_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,1,?,?,?)").bind(id, context.workspaceId, name, secret.slice(0, 12), await contentHash(secret), JSON.stringify(scopes), context.userId, validDate(input.expiresAt), now, now).run(); return { action, id, apiKey: secret, keyPrefix: secret.slice(0, 12), warning: "API Key 只显示一次；请立即保存。" }; }
  if (action === "api_client.revoke") { const id = requiredString(input.id, "id"); await db.prepare("UPDATE api_clients SET enabled=0,revoked_at=?,updated_at=? WHERE id=? AND workspace_id=?").bind(now, now, id, context.workspaceId).run(); return { action, id }; }
  if (action === "webhook.save") { const endpointUrl = validateWebhookUrl(requiredString(input.endpointUrl, "endpointUrl", 2000)); const events = stringArray(input.eventTypes); if (!events.length || events.some((event) => !["research.version.published","workflow.run.completed","workflow.run.failed","*"].includes(event))) throw new HttpError(400, "INVALID_EVENTS", "Webhook event 类型不合法"); const secret = optionalString(input.secret, 1000) ?? randomToken(); const encrypted = await encryptConnectorSecret(secret); const id = crypto.randomUUID(); await db.prepare("INSERT INTO webhook_subscriptions (id,workspace_id,name,endpoint_url,event_types_json,secret_ciphertext,secret_iv,enabled,verification_status,consecutive_failures,created_at,updated_at) VALUES (?,?,?,?,?,?,?,1,'pending',0,?,?)").bind(id, context.workspaceId, requiredString(input.name, "name", 100), endpointUrl, JSON.stringify(events), encrypted.ciphertext, encrypted.iv, now, now).run(); return { action, id, signingSecret: secret, warning: "签名密钥只显示一次；使用 x-alphalens-signature 验签。" }; }
  if (action === "webhook.disable") { const id = requiredString(input.id, "id"); await db.prepare("UPDATE webhook_subscriptions SET enabled=0,verification_status='disabled',updated_at=? WHERE id=? AND workspace_id=?").bind(now, id, context.workspaceId).run(); return { action, id }; }
  throw new HttpError(400, "UNKNOWN_ACTION", `不支持的平台操作：${action}`);
}

async function ensurePlatformDefaults(context: AuthContext) {
  const db = getD1(); const now = new Date().toISOString(); const workflowId = await stableId("rwf", `${context.workspaceId}:evidence-first-equity-research`); const workflowLogicalId = await stableId("rwl", workflowId); const workflowVersionId = await stableId("rwv", `${workflowLogicalId}:1`); const workflow: WorkflowDefinition = { maxParallelism: 3, failurePolicy: "continue_independent", nodes: [{ id: "filings", type: "agent", role: "filing_analyst", skillSlug: "earnings-preview", objective: "核验 SEC 与公司 IR 的第一方事实、财务口径和时间边界" }, { id: "expectations", type: "agent", role: "expectations_analyst", skillSlug: "implied-expectations", objective: "识别市场一致预期、价格隐含要求和关键分歧" }, { id: "challenger", type: "agent", role: "risk_challenger", skillSlug: "thesis-challenger", objective: "寻找最强反方证据、来源冲突、证伪条件与遗漏风险" }, { id: "arbitrate", type: "arbitration", dependsOn: ["filings", "expectations", "challenger"] }] };
  const suiteId = await stableId("bms", `${context.workspaceId}:research-quality-core`);
  await db.batch([db.prepare("INSERT OR IGNORE INTO research_workflows (id,workspace_id,slug,name,description,owner_user_id,visibility,created_at,updated_at) VALUES (?,?,?,?,?,?, 'workspace',?,?)").bind(workflowId, context.workspaceId, "evidence-first-equity-research", "Evidence-first Equity Research", "三路独立研究与可解释仲裁", context.userId, now, now), db.prepare("INSERT OR IGNORE INTO research_workflow_versions (id,logical_id,version,workflow_id,workspace_id,semver,definition_json,input_schema_json,output_schema_json,status,checksum,published_at,created_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,'1.0.0',?,'{}','{}','published',?,?,?,?,?)").bind(workflowVersionId, workflowLogicalId, 1, workflowId, context.workspaceId, JSON.stringify(workflow), await contentHash(workflow), now, context.userId, now, now), db.prepare("INSERT OR IGNORE INTO benchmark_suites (id,workspace_id,slug,name,description,rubric_json,version,owner_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,1,?,?,?)").bind(suiteId, context.workspaceId, "research-quality-core", "Research Quality Core", "证据、权威性、反证、新鲜度、Groundedness 与时间完整性", JSON.stringify({ passScore: .75, leakageTolerance: 0 }), context.userId, now, now)]);
  for (const benchmark of defaultBenchmarkCases) { const id = await stableId("bmc", `${suiteId}:${benchmark.name}`); await db.prepare("INSERT OR IGNORE INTO benchmark_cases (id,workspace_id,suite_id,name,input_json,expected_json,tags_json,as_of,created_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(id, context.workspaceId, suiteId, benchmark.name, JSON.stringify(benchmark.input), JSON.stringify(benchmark.expected), JSON.stringify(benchmark.tags), benchmark.asOf, now).run(); }
  for (const route of defaultRoutes) { const id = await stableId("pvr", `${context.workspaceId}:${route.capability}:${route.provider}`); await db.prepare("INSERT OR IGNORE INTO provider_routes (id,workspace_id,category,provider,capability,priority,license_scope,allowed_use,freshness_seconds,enabled,config_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,1,'{}',?,?)").bind(id, context.workspaceId, route.category, route.provider, route.capability, route.priority, route.licenseScope, route.allowedUse, route.freshnessSeconds, now, now).run(); }
  for (const template of defaultKpis) { const modelId = await stableId("kpm", `${context.workspaceId}:${template.slug}`); const logicalId = await stableId("kpl", modelId); const versionId = await stableId("kpv", `${logicalId}:1`); await db.batch([db.prepare("INSERT OR IGNORE INTO kpi_models (id,workspace_id,slug,name,sector,industry,owner_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(modelId, context.workspaceId, template.slug, template.name, template.sector, template.industry, context.userId, now, now), db.prepare("INSERT OR IGNORE INTO kpi_model_versions (id,logical_id,version,kpi_model_id,workspace_id,semver,metrics_json,validation_rules_json,status,checksum,published_at,created_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,'1.0.0',?,'[]','published',?,?,?,?,?)").bind(versionId, logicalId, 1, modelId, context.workspaceId, JSON.stringify(template.metrics), await contentHash(template.metrics), now, context.userId, now, now)]); }
  for (const skill of defaultSkills) { const skillId = await stableId("rsk", `${context.workspaceId}:${skill.name}`); const logicalId = await stableId("rsl", skillId); const versionId = await stableId("rsv", `${logicalId}:1`); const installId = await stableId("rsi", `${context.workspaceId}:${versionId}`); const validation = validateSkillManifest(skill); await db.batch([db.prepare("INSERT OR IGNORE INTO research_skills (id,workspace_id,slug,name,description,publisher_user_id,visibility,category,created_at,updated_at) VALUES (?,?,?,?,?,?, 'marketplace',?,?,?)").bind(skillId, context.workspaceId, skill.name, skill.displayName, skill.description, context.userId, skill.category, now, now), db.prepare("INSERT OR IGNORE INTO research_skill_versions (id,logical_id,version,skill_id,workspace_id,semver,manifest_json,instructions,input_schema_json,output_schema_json,permissions_json,status,checksum,published_at,validation_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?, '{}','{}',?,'published',?,?,?, ?,?)").bind(versionId, logicalId, 1, skillId, context.workspaceId, skill.version, JSON.stringify(skill), skill.instructions, JSON.stringify(skill.permissions), await contentHash(skill), now, JSON.stringify(validation), now, now), db.prepare("INSERT OR IGNORE INTO skill_installations (id,workspace_id,skill_version_id,installed_by_user_id,enabled,granted_permissions_json,installed_at,updated_at) VALUES (?,?,?,?,1,?,?,?)").bind(installId, context.workspaceId, versionId, context.userId, JSON.stringify(skill.permissions), now, now)]); }
}

async function loadProviderRoutes(workspaceId: string): Promise<ProviderRoute[]> { const rows = await getD1().prepare("SELECT pr.provider,pr.category,pr.capability,pr.priority,pr.enabled,pr.license_scope AS licenseScope,pr.allowed_use AS allowedUse,pr.max_latency_ms AS maxLatencyMs,pr.max_cost_usd AS maxCostUsd,pr.freshness_seconds AS freshnessSeconds,ps.status AS health,ps.latency_ms AS latencyMs FROM provider_routes pr LEFT JOIN provider_state ps ON ps.provider=pr.provider WHERE pr.workspace_id=?").bind(workspaceId).all<ProviderRoute>(); return rows.results; }
async function assertArtifactVersion(workspaceId: string, id: string) { if (!await getD1().prepare("SELECT id FROM research_artifact_versions WHERE id=? AND workspace_id=?").bind(id, workspaceId).first()) throw new HttpError(404, "ARTIFACT_VERSION_NOT_FOUND", "研究版本不存在"); }
function validateMetrics(metrics: unknown[]) { for (const metric of metrics) { if (!isRecord(metric) || typeof metric.key !== "string" || typeof metric.label !== "string" || typeof metric.definition !== "string" || typeof metric.unit !== "string") throw new HttpError(400, "INVALID_KPI", "每个 KPI 必须包含 key、label、definition 和 unit"); } }
function parseColumns(row: JsonRecord) { const result = { ...row }; for (const key of Object.keys(result).filter((item) => item.endsWith("Json"))) { result[key.slice(0, -4)] = parse(result[key]); delete result[key]; } return result; }
function parse(value: unknown): unknown { if (typeof value !== "string") return value ?? null; try { return JSON.parse(value); } catch { return null; } }
function permissionSubset(granted: JsonRecord, requested: unknown) { const declared = isRecord(requested) ? requested : {}; return Object.entries(granted).every(([key, values]) => Array.isArray(values) && Array.isArray(declared[key]) && values.every((value) => (declared[key] as unknown[]).includes(value))); }
function requiredString(value: unknown, name: string, max = 200) { if (typeof value !== "string" || !value.trim() || value.trim().length > max) throw new HttpError(400, "INVALID_ARGUMENT", `${name} 格式不正确`); return value.trim(); }
function optionalString(value: unknown, max = 200) { return typeof value === "string" && value.trim() ? value.trim().slice(0, max) : null; }
function slugValue(value: unknown) { const result = requiredString(value, "slug", 64).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); if (!/^[a-z][a-z0-9-]{1,62}$/.test(result)) throw new HttpError(400, "INVALID_SLUG", "slug 必须以字母开头并使用 kebab-case"); return result; }
function semver(value: unknown, version: number) { const result = typeof value === "string" ? value.trim() : `0.${version}.0`; if (!/^\d+\.\d+\.\d+$/.test(result)) throw new HttpError(400, "INVALID_SEMVER", "版本必须使用 semver"); return result; }
function requireObject(value: unknown): JsonRecord { if (!isRecord(value)) throw new HttpError(400, "INVALID_OBJECT", "对象格式不正确"); return value; }
function requireArray(value: unknown, name: string, max: number) { if (!Array.isArray(value) || !value.length || value.length > max) throw new HttpError(400, "INVALID_ARRAY", `${name} 需要 1–${max} 项`); return value; }
function objectOrEmpty(value: unknown) { return isRecord(value) ? value : {}; }
function arrayOrEmpty(value: unknown) { return Array.isArray(value) ? value.slice(0, 100) : []; }
function stringArray(value: unknown) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string").map((item) => item.trim()).filter(Boolean).slice(0, 100) : []; }
function isRecord(value: unknown): value is JsonRecord { return Boolean(value && typeof value === "object" && !Array.isArray(value)); }
function enumValue<T extends string>(value: unknown, allowed: readonly T[], fallback: T): T { return typeof value === "string" && allowed.includes(value as T) ? value as T : fallback; }
function integer(value: unknown, min: number, max: number, fallback: number) { const number = Number(value); return Number.isInteger(number) && number >= min && number <= max ? number : fallback; }
function nullableInteger(value: unknown) { const number = Number(value); return value !== null && value !== "" && Number.isInteger(number) ? number : null; }
function nullableDecimal(value: unknown) { const number = Number(value); return value !== null && value !== "" && Number.isFinite(number) ? number : null; }
function booleanValue(value: unknown, fallback: boolean) { return typeof value === "boolean" ? value : fallback; }
function validDate(value: unknown) { return typeof value === "string" && !Number.isNaN(Date.parse(value)) ? new Date(value).toISOString() : null; }
function roleRank(role: string) { return ({ viewer: 1, editor: 2, owner: 3 } as Record<string, number>)[role] ?? 0; }
function randomToken() { const bytes = crypto.getRandomValues(new Uint8Array(32)); return [...bytes].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }

const defaultRoutes = [{ category: "Company Filings & IR", provider: "sec-edgar", capability: "filings", priority: 10, licenseScope: "public-sec-fair-access", allowedUse: "research,display", freshnessSeconds: 21600 }, { category: "Company Filings & IR", provider: "issuer-ir", capability: "issuer-events", priority: 20, licenseScope: "issuer-publication-link-and-excerpt", allowedUse: "research,display", freshnessSeconds: 21600 }, { category: "Market Data & Estimates", provider: "alpha-vantage-market", capability: "market-quote", priority: 30, licenseScope: "byo-commercial-or-authorized", allowedUse: "research,display", freshnessSeconds: 900 }, { category: "Market Data & Estimates", provider: "alpha-vantage-consensus", capability: "consensus", priority: 30, licenseScope: "byo-commercial-or-authorized", allowedUse: "research", freshnessSeconds: 43200 }];
const defaultKpis = [{ slug: "semiconductors-core", name: "Semiconductors Core", sector: "Information Technology", industry: "Semiconductors", metrics: [{ key: "data_center_revenue", label: "Data Center Revenue", definition: "公司披露的数据中心收入，保持报告币种与财季口径", unit: "currency" }, { key: "gross_margin", label: "Gross Margin", definition: "GAAP 毛利率；Non-GAAP 单列", unit: "percent" }, { key: "inventory_days", label: "Inventory Days", definition: "期末库存相对季度成本的标准化天数", unit: "days" }, { key: "advanced_packaging_supply", label: "Advanced Packaging Supply", definition: "公司或供应链一方披露的先进封装供给指标", unit: "index" }] }, { slug: "software-saas-core", name: "Software / SaaS Core", sector: "Information Technology", industry: "Software", metrics: [{ key: "arr", label: "ARR", definition: "公司定义的年度经常性收入，保留定义变更", unit: "currency" }, { key: "net_revenue_retention", label: "Net Revenue Retention", definition: "同一客户群净留存率", unit: "percent" }, { key: "remaining_performance_obligations", label: "RPO", definition: "剩余履约义务及 current RPO", unit: "currency" }, { key: "fcf_margin", label: "FCF Margin", definition: "自由现金流相对收入，披露 SBC 口径", unit: "percent" }] }, { slug: "banks-core", name: "Banks Core", sector: "Financials", industry: "Banks", metrics: [{ key: "net_interest_margin", label: "Net Interest Margin", definition: "净利息收入相对生息资产", unit: "percent" }, { key: "cet1_ratio", label: "CET1 Ratio", definition: "监管资本口径 CET1 比率", unit: "percent" }, { key: "net_charge_off_ratio", label: "Net Charge-off Ratio", definition: "净核销相对平均贷款", unit: "percent" }, { key: "deposit_beta", label: "Deposit Beta", definition: "存款成本相对政策利率变化的敏感度", unit: "ratio" }] }];
const defaultSkills = [{ name: "earnings-preview", displayName: "Earnings Preview", description: "构建财报前预期差、KPI、管理层问题、情景与证伪条件。", version: "1.0.0", category: "earnings", inputs: ["ticker", "fiscal_period", "as_of"], outputs: ["preview", "watch_items"], permissions: { network: ["sec.gov"], data: ["company_filings_ir", "market_data_estimates"], write: ["workspace/research"] }, runtime: { maxSeconds: 300, modelPolicy: "approved-research-models" }, instructions: "先核验第一方披露与市场预期，再输出分歧、KPI、情景、反方证据和证伪条件。" }, { name: "thesis-challenger", displayName: "Thesis Challenger", description: "独立寻找最强反方证据、来源冲突、逻辑跳跃与时间穿越。", version: "1.0.0", category: "quality", inputs: ["thesis", "evidence", "as_of"], outputs: ["challenge", "missing_evidence"], permissions: { network: ["sec.gov"], data: ["company_filings_ir"], write: ["workspace/research"] }, runtime: { maxSeconds: 180, modelPolicy: "approved-research-models" }, instructions: "不重复主论点；逐条检查证据权威性、反证、口径、as_of 和证伪条件。" }, { name: "implied-expectations", displayName: "Implied Expectations", description: "从价格和估值假设反推市场要求的增长、利润率或事件概率。", version: "1.0.0", category: "valuation", inputs: ["price", "model", "assumptions", "as_of"], outputs: ["implied_expectations", "sensitivity"], permissions: { data: ["market_data_estimates"], write: ["workspace/research"] }, runtime: { maxSeconds: 120, modelPolicy: "deterministic-first" }, instructions: "优先使用确定性反向求解；披露全部假设和敏感性，不输出确定性目标价。" }];
const defaultBenchmarkCases = [
  { name: "Semiconductor earnings temporal boundary", input: { sector: "semiconductors", task: "earnings_deep_dive" }, expected: { primarySourcesRequired: true, leakageViolations: 0, contradictionRequired: true }, tags: ["semiconductors", "earnings", "time-travel"], asOf: "2025-01-31T21:00:00.000Z" },
  { name: "SaaS KPI definition change", input: { sector: "software", task: "kpi_normalization" }, expected: { preserveDefinitionChanges: true, primarySourcesRequired: true, unsupportedClaims: 0 }, tags: ["saas", "kpi", "definitions"], asOf: "2025-01-31T21:00:00.000Z" },
  { name: "Bank credit conflict", input: { sector: "banks", task: "source_conflict" }, expected: { preserveConflictingValues: true, contradictionRequired: true, leakageViolations: 0 }, tags: ["banks", "credit", "conflict"], asOf: "2025-01-31T21:00:00.000Z" },
];
