import { getD1 } from "../../db";
import { stableId } from "../core/ids";
import { decryptConnectorSecret } from "../workbench/connectors";
export { validateWebhookUrl } from "./webhook-security";
import { validateWebhookUrl } from "./webhook-security";

export async function queueWebhookEvent(workspaceId: string, eventType: string, payload: Record<string, unknown>, eventId = crypto.randomUUID()) {
  const db = getD1(); const now = new Date().toISOString(); const subscriptions = await db.prepare("SELECT id,event_types_json AS eventTypesJson FROM webhook_subscriptions WHERE workspace_id=? AND enabled=1 AND verification_status<>'disabled'").bind(workspaceId).all<{ id: string; eventTypesJson: string }>(); let queued = 0;
  for (const subscription of subscriptions.results) { const types = parseArray(subscription.eventTypesJson); if (!types.includes(eventType) && !types.includes("*")) continue; const id = await stableId("whd", `${subscription.id}:${eventId}`); const result = await db.prepare("INSERT OR IGNORE INTO webhook_deliveries (id,workspace_id,subscription_id,event_id,event_type,payload_json,status,attempts,next_attempt_at,created_at,updated_at) VALUES (?,?,?,?,?,?,'queued',0,?,?,?)").bind(id, workspaceId, subscription.id, eventId, eventType, JSON.stringify({ id: eventId, type: eventType, createdAt: now, data: payload }), now, now, now).run(); queued += result.meta.changes ?? 0; }
  return queued;
}

export async function drainWebhookDeliveries(limit = 20) {
  const db = getD1(); const now = new Date().toISOString(); const rows = await db.prepare("SELECT d.id,d.event_id AS eventId,d.event_type AS eventType,d.payload_json AS payloadJson,d.attempts,s.id AS subscriptionId,s.endpoint_url AS endpointUrl,s.secret_ciphertext AS secretCiphertext,s.secret_iv AS secretIv FROM webhook_deliveries d JOIN webhook_subscriptions s ON s.id=d.subscription_id WHERE d.status IN ('queued','failed') AND d.next_attempt_at<=? AND d.attempts<8 AND s.enabled=1 ORDER BY d.created_at LIMIT ?").bind(now, Math.min(limit, 50)).all<{ id: string; eventId: string; eventType: string; payloadJson: string; attempts: number; subscriptionId: string; endpointUrl: string; secretCiphertext: string; secretIv: string }>(); const results = [];
  for (const row of rows.results) { const claimed = await db.prepare("UPDATE webhook_deliveries SET status='sending',attempts=attempts+1,updated_at=? WHERE id=? AND status IN ('queued','failed')").bind(now, row.id).run(); if (!claimed.meta.changes) continue;
    try { validateWebhookUrl(row.endpointUrl); const secret = await decryptConnectorSecret(row.secretCiphertext, row.secretIv); const timestamp = Math.floor(Date.now() / 1000).toString(); const signature = await hmac(secret, `${timestamp}.${row.payloadJson}`); const response = await fetch(row.endpointUrl, { method: "POST", redirect: "error", headers: { "content-type": "application/json", "user-agent": "AlphaLens-Webhooks/1.0", "x-alphalens-event": row.eventType, "x-alphalens-delivery": row.eventId, "x-alphalens-signature": `t=${timestamp},v1=${signature}`, "idempotency-key": row.eventId }, body: row.payloadJson, signal: AbortSignal.timeout(10_000) }); const responseBody = (await response.text()).slice(0, 1000); if (!response.ok) throw new DeliveryError(response.status, responseBody); const completed = new Date().toISOString(); await db.batch([db.prepare("UPDATE webhook_deliveries SET status='delivered',response_status=?,response_body=?,delivered_at=?,error_message=NULL,updated_at=? WHERE id=?").bind(response.status, responseBody, completed, completed, row.id), db.prepare("UPDATE webhook_subscriptions SET verification_status='verified',consecutive_failures=0,last_delivery_at=?,updated_at=? WHERE id=?").bind(completed, completed, row.subscriptionId)]); results.push({ id: row.id, status: "delivered" }); }
    catch (error) { const attempts = row.attempts + 1; const terminal = attempts >= 8; const next = new Date(Date.now() + Math.min(6 * 3600_000, 30_000 * 2 ** Math.min(attempts, 8))).toISOString(); const status = error instanceof DeliveryError ? error.status : null; const message = error instanceof Error ? error.message : String(error); const failedAt = new Date().toISOString(); await db.batch([db.prepare("UPDATE webhook_deliveries SET status=?,next_attempt_at=?,response_status=?,error_message=?,updated_at=? WHERE id=?").bind(terminal ? "dead_letter" : "failed", next, status, message.slice(0, 1000), failedAt, row.id), db.prepare("UPDATE webhook_subscriptions SET verification_status=CASE WHEN consecutive_failures>=4 THEN 'failing' ELSE verification_status END,consecutive_failures=consecutive_failures+1,updated_at=? WHERE id=?").bind(failedAt, row.subscriptionId)]); results.push({ id: row.id, status: terminal ? "dead_letter" : "failed" }); }
  }
  return results;
}

async function hmac(secret: string, message: string) { const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const signature = new Uint8Array(await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(message))); return [...signature].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
function parseArray(value: string) { try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === "string") : []; } catch { return []; } }
class DeliveryError extends Error { status: number; constructor(status: number, body: string) { super(`Webhook ${status}: ${body || "delivery failed"}`); this.status = status; } }
