"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type Row = Record<string, unknown>;
type PlatformData = { workflows: Row[]; kpiModels: Row[]; providerRoutes: Row[]; skills: Row[]; runs: Row[]; selectedRun: Row | null; artifacts: Row[]; comments: Row[]; approvals: Row[]; evaluations: Row[]; benchmarkSuites: Row[]; apiClients: Row[]; webhooks: Row[]; platformVersion: string; asOf: string };
const starterWorkflow = JSON.stringify({ maxParallelism: 3, failurePolicy: "continue_independent", nodes: [{ id: "fundamentals", type: "agent", role: "fundamental_analyst", skillSlug: "earnings-preview", objective: "核验第一方披露与关键 KPI" }, { id: "challenger", type: "agent", role: "risk_challenger", skillSlug: "thesis-challenger", objective: "独立查找反证、冲突与时间穿越" }, { id: "arbitrate", type: "arbitration", dependsOn: ["fundamentals", "challenger"] }] }, null, 2);

export default function ResearchPlatform() {
  const [data, setData] = useState<PlatformData | null>(null); const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  const [ticker, setTicker] = useState("NVDA"); const [question, setQuestion] = useState("核验增长、估值隐含预期与最强反方证据"); const [workflowJson, setWorkflowJson] = useState(starterWorkflow);
  const [routeCapability, setRouteCapability] = useState("filings"); const [routeResult, setRouteResult] = useState<Row | null>(null); const [artifactTitle, setArtifactTitle] = useState("NVDA Evidence-first Research Memo"); const [artifactBody, setArtifactBody] = useState("# 研究结论\n\n待团队核验并审批后发布。"); const [secret, setSecret] = useState("");
  const load = useCallback(async (runId?: string) => { const response = await fetch(`/api/v1/platform${runId ? `?runId=${encodeURIComponent(runId)}` : ""}`, { cache: "no-store" }); const payload = await response.json() as { data?: PlatformData; error?: { message?: string } }; if (!response.ok || !payload.data) throw new Error(payload.error?.message ?? "平台数据加载失败"); setData(payload.data); }, []);
  useEffect(() => {
    let active = true;
    fetch("/api/v1/platform", { cache: "no-store" }).then(async (response) => { const payload = await response.json() as { data?: PlatformData; error?: { message?: string } }; if (!response.ok || !payload.data) throw new Error(payload.error?.message ?? "平台数据加载失败"); return payload.data; }).then((next) => { if (active) setData(next); }).catch((error: unknown) => { if (active) setMessage(error instanceof Error ? error.message : "平台数据加载失败"); });
    return () => { active = false; };
  }, []);

  async function action(input: Row, refresh = true) { setBusy(String(input.action)); setMessage(""); try { const response = await fetch("/api/v1/platform", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) }); const payload = await response.json() as { data?: Row; error?: { message?: string } }; if (!response.ok || !payload.data) throw new Error(payload.error?.message ?? "操作失败"); if (typeof payload.data.apiKey === "string") setSecret(payload.data.apiKey); if (typeof payload.data.signingSecret === "string") setSecret(payload.data.signingSecret); setMessage(String(payload.data.warning ?? "操作已完成并写入审计日志")); if (refresh) await load(typeof payload.data.id === "string" && input.action === "workflow.run" ? payload.data.id : undefined); return payload.data; } catch (error) { setMessage(error instanceof Error ? error.message : "操作失败"); return null; } finally { setBusy(""); } }
  async function saveWorkflow(event: FormEvent) { event.preventDefault(); try { await action({ action: "workflow.save", name: "Custom Evidence Workflow", slug: "custom-evidence-workflow", description: "Workspace 可配置研究 DAG", status: "published", definition: JSON.parse(workflowJson) }); } catch { setMessage("Workflow JSON 格式不正确"); } }
  const selected = data?.selectedRun as (Row & { steps?: Row[]; arbitration?: Row }) | null; const latestArtifact = data?.artifacts[0]; const pendingApproval = data?.approvals.find((item) => item.status === "pending");

  return <>
    <section className="page-title platform-title"><div><p className="section-kicker">P3 / RESEARCH PLATFORM</p><h1>把研究方法，<em>变成可治理的平台能力。</em></h1><p>版本化 Workflow、行业 KPI、动态数据路由、Skill 与多 Agent 仲裁，共用同一条审计链。</p></div><span className="platform-version">{data?.platformVersion ?? "0.5.0-beta"}</span></section>
    {message && <div className="platform-notice" role="status">{message}</div>}
    <section className="platform-metrics">
      <Metric label="Published workflows" value={data?.workflows.length ?? 0} detail="DAG + immutable versions" />
      <Metric label="Industry KPI models" value={data?.kpiModels.length ?? 0} detail="definition + validation" />
      <Metric label="Provider routes" value={data?.providerRoutes.length ?? 0} detail="license-aware fallback" />
      <Metric label="Research skills" value={data?.skills.length ?? 0} detail="least-privilege installs" />
    </section>

    <section className="platform-grid">
      <article className="panel platform-card wide"><div className="panel-head"><div>Workflow Control Plane</div><span>多 Agent DAG · 版本化 · 可恢复</span></div>
        <form className="platform-inline" onSubmit={(event) => { event.preventDefault(); action({ action: "workflow.run", workflowVersionId: data?.workflows[0]?.versionId, ticker, question, asOf: new Date().toISOString() }); }}><input value={ticker} onChange={(e) => setTicker(e.target.value.toUpperCase())} aria-label="Ticker" /><input value={question} onChange={(e) => setQuestion(e.target.value)} aria-label="研究问题" /><button disabled={Boolean(busy)}>运行 Workflow</button></form>
        <div className="workflow-map">{((data?.workflows[0]?.definition as { nodes?: Row[] })?.nodes ?? []).map((node, index) => <div key={String(node.id)}><span>{String(index + 1).padStart(2, "0")}</span><strong>{String(node.role ?? node.type)}</strong><small>{String(node.skillSlug ?? "policy node")}</small></div>)}</div>
        {selected && <div className="run-inspector"><div><strong>{String(selected.ticker ?? "—")} · {String(selected.workflowName)}</strong><span className="status-chip">{String(selected.status)}</span></div>{(selected.steps ?? []).map((step) => <button key={String(step.id)}><span>{String(step.nodeKey)}</span><small>{String(step.agentRole ?? step.nodeType)}</small><b>{String(step.status)}</b></button>)}{selected.arbitration && <p><b>仲裁解释：</b>{((selected.arbitration.explanation as string[]) ?? []).join(" ")} 置信度 {Math.round(Number(selected.arbitration.confidence ?? 0) * 100)}%</p>}</div>}
      </article>
      <article className="panel platform-card"><div className="panel-head"><div>Provider Router</div><span>许可 / 健康 / 成本 / 新鲜度</span></div>
        <div className="provider-list">{data?.providerRoutes.map((route) => <div key={String(route.id)}><span className={route.health === "open" ? "route-dot bad" : "route-dot"} /><strong>{String(route.provider)}</strong><small>{String(route.capability)}</small><b>P{String(route.priority)}</b></div>)}</div>
        <form className="platform-inline compact" onSubmit={async (event) => { event.preventDefault(); const result = await action({ action: "provider.route.preview", request: { capability: routeCapability, use: "research", requireFreshnessSeconds: 86400 } }, false); setRouteResult(result); }}><select value={routeCapability} onChange={(e) => setRouteCapability(e.target.value)}><option>filings</option><option>issuer-events</option><option>market-quote</option><option>consensus</option></select><button>预演路由</button></form>
        {routeResult && <p className="route-explanation">{String(routeResult.explanation)}</p>}
      </article>

      <article className="panel platform-card"><div className="panel-head"><div>Industry KPI Registry</div><span>可追溯定义</span></div><div className="kpi-models">{data?.kpiModels.map((model) => <div key={String(model.id)}><strong>{String(model.name)}</strong><small>{String(model.industry)} · {String(model.semver)}</small><p>{Array.isArray(model.metrics) ? model.metrics.map((metric: Row) => metric.label).join(" · ") : ""}</p></div>)}</div></article>
      <article className="panel platform-card wide"><div className="panel-head"><div>Research Skill Marketplace</div><span>Manifest 校验 · 显式权限</span></div><div className="skill-market">{data?.skills.map((skill) => <div key={String(skill.versionId)}><span>{String(skill.category).toUpperCase()}</span><strong>{String(skill.name)}</strong><p>{String(skill.description)}</p><small>{String(skill.semver)} · {skill.installed ? "已安装" : "未安装"}</small>{!skill.installed && <button onClick={() => action({ action: "skill.install", skillVersionId: skill.versionId, grantedPermissions: {} })}>最小权限安装</button>}</div>)}</div></article>

      <article className="panel platform-card wide"><div className="panel-head"><div>Team Review & Release</div><span>评论 → 审批 → 不可变发布</span></div>
        <div className="release-flow"><textarea value={artifactBody} onChange={(e) => setArtifactBody(e.target.value)} aria-label="研究内容" /><div><input value={artifactTitle} onChange={(e) => setArtifactTitle(e.target.value)} aria-label="版本标题" /><button onClick={() => action({ action: "artifact.save", workflowRunId: selected?.id, title: artifactTitle, content: { markdown: artifactBody }, asOf: new Date().toISOString() })}>保存新版本</button>{latestArtifact && <><button onClick={() => action({ action: "comment.add", artifactVersionId: latestArtifact.versionId, body: "请复核来源权威性、反方证据与 as_of。", anchor: { section: "conclusion" } })}>添加审阅评论</button>{data?.comments.find((item) => item.artifactVersionId === latestArtifact.versionId && item.status === "open") && <button onClick={() => action({ action: "comment.resolve", id: data.comments.find((item) => item.artifactVersionId === latestArtifact.versionId && item.status === "open")?.id })}>解决最近评论</button>}<button onClick={() => action({ action: "approval.request", artifactVersionId: latestArtifact.versionId, requiredRole: "owner" })}>请求审批</button></>}{pendingApproval && <button onClick={() => action({ action: "approval.decide", id: pendingApproval.id, decision: "approved", note: "已复核来源、冲突和时间边界" })}>批准待审版本</button>}{latestArtifact?.status === "approved" && <button onClick={() => action({ action: "artifact.publish", artifactVersionId: latestArtifact.versionId })}>发布研究版本</button>}</div></div>
        <div className="review-ledger"><span>版本 {data?.artifacts.length ?? 0}</span><span>开放评论 {data?.comments.filter((item) => item.status === "open").length ?? 0}</span><span>待审批 {data?.approvals.filter((item) => item.status === "pending").length ?? 0}</span><span>已发布 {data?.artifacts.filter((item) => item.status === "published").length ?? 0}</span></div>
      </article>

      <article className="panel platform-card"><div className="panel-head"><div>Quality Benchmark</div><span>可解释评分</span></div><p>核心基准检查证据覆盖、第一方来源、反证、新鲜度、groundedness 与时间完整性。</p><button className="platform-action" onClick={() => data?.benchmarkSuites[0] && action({ action: "benchmark.evaluate", suiteId: data.benchmarkSuites[0].id, metrics: { citations: 12, primaryCitations: 8, contradictions: 3, staleSources: 1, unsupportedClaims: 0, leakageViolations: 0 }, asOf: new Date().toISOString() })}>运行基准评估</button>{data?.evaluations[0] && <div className="quality-score"><strong>{Math.round(Number((data.evaluations[0].scores as Row)?.overall ?? 0) * 100)}</strong><span>/100<br />{Number(data.evaluations[0].passedCount) ? "PASS" : "REVIEW"}</span></div>}</article>
      <article className="panel platform-card"><div className="panel-head"><div>Open API & Webhooks</div><span>scoped · signed · retried</span></div><div className="external-controls"><button onClick={() => action({ action: "api_client.create", name: "Research Integration", scopes: ["research:write", "research:read", "artifacts:read"] })}>创建 API Key</button><button onClick={() => action({ action: "webhook.save", name: "Research Releases", endpointUrl: "https://example.com/alphalens-webhook", eventTypes: ["research.version.published", "workflow.run.completed", "workflow.run.failed"] })}>创建签名 Webhook</button></div>{secret && <div className="one-time-secret"><span>仅显示一次</span><code>{secret}</code></div>}<p className="api-hint">POST /api/open/v1/research<br />GET /api/open/v1/runs/:runId<br />GET /api/open/v1/artifacts/:versionId</p></article>

      <article className="panel platform-card full"><div className="panel-head"><div>Workflow Designer</div><span>JSON DAG · checksum · semver</span></div><form onSubmit={saveWorkflow}><textarea className="workflow-editor" value={workflowJson} onChange={(e) => setWorkflowJson(e.target.value)} aria-label="Workflow JSON" /><button className="platform-action" disabled={Boolean(busy)}>校验并发布新版本</button></form></article>
    </section>
  </>;
}

function Metric({ label, value, detail }: { label: string; value: number; detail: string }) { return <article><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }
