"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Position = { id: string; ticker: string; issuerName?: string; positionType: "long" | "short" | "watch"; shares: number; currentPrice?: number; marketValue?: number; currency?: string; sector?: string; beta?: number; advUsd?: number; dataStatus?: string; factorExposures?: Record<string, number>; eventTags?: string[] };
type Exposure = Record<string, number>;
type PortfolioData = {
  portfolios: Array<{ id: string; name: string; baseCurrency: string }>;
  portfolio: { id: string; name: string; baseCurrency: string };
  positions: Position[]; watchItems: Array<{ ticker: string; issuerName?: string }>;
  policy: { nav: number; maxPositionWeight: number; maxSectorWeight: number; maxFactorExposure: number; maxEventClusterWeight: number; scenarioLossBudgetBps: number; absoluteLossCapBps: number; correlationLookbackDays?: number; exitParticipationRate: number };
  risk: { nav: number; grossExposure: number; netExposure: number; betaAdjustedNet: number; top5Weight: number; hhi: number; effectivePositions: number; weights: Array<{ ticker: string; weight: number; absoluteWeight: number }>; exposures: { sector: Exposure; factor: Exposure; currency: Exposure; event: Exposure }; liquidity: Array<{ ticker: string; daysToExit: number | null }>; warnings: string[] };
  correlation: { tickers: string[]; matrix: Record<string, Record<string, number | null>>; coverage: number; warnings: string[] };
  scenarios: Array<{ id: string; logicalId: string; name: string; version: number; shocks: unknown[]; result?: { lossBps?: number; budgetStatus?: string } }>;
  catalysts: Array<{ id: string; ticker: string; title: string; eventAt?: string; dateStatus: string; isStale?: boolean }>;
  generatedConditions: Array<{ key: string; ticker?: string; severity: string; conditionType: string; message: string }>;
  savedConditions: Array<{ id: string; ticker?: string; severity: string; conditionType: string; status: string; message: string }>;
  asOf: string; executionPolicy: string;
};

export default function PortfolioWorkbench() {
  const [data, setData] = useState<PortfolioData | null>(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  const [ticker, setTicker] = useState(""); const [positionType, setPositionType] = useState("long"); const [shares, setShares] = useState(0); const [price, setPrice] = useState(0); const [sector, setSector] = useState(""); const [positionCurrency, setPositionCurrency] = useState("USD"); const [beta, setBeta] = useState(1); const [adv, setAdv] = useState(0); const [factors, setFactors] = useState("growth:1"); const [events, setEvents] = useState("earnings");
  const [scenarioName, setScenarioName] = useState("行业需求下行"); const [shockDimension, setShockDimension] = useState("sector"); const [shockKey, setShockKey] = useState("Technology"); const [shockPercent, setShockPercent] = useState(-15);
  const [returnsText, setReturnsText] = useState("");

  const load = useCallback(async (portfolioId?: string) => {
    setLoading(true); try { const response = await fetch(`/api/v1/portfolio${portfolioId ? `?portfolioId=${encodeURIComponent(portfolioId)}` : ""}`, { cache: "no-store" }); const payload = await response.json() as { data?: PortfolioData; error?: { message: string } }; if (!response.ok || !payload.data) throw new Error(payload.error?.message ?? "组合读取失败"); setData(payload.data); setMessage(""); }
    catch (error) { setMessage(error instanceof Error ? error.message : "组合读取失败"); } finally { setLoading(false); }
  }, []);
  useEffect(() => {
    let active = true;
    fetch("/api/v1/portfolio", { cache: "no-store" }).then(async (response) => { const payload = await response.json() as { data?: PortfolioData; error?: { message: string } }; if (!response.ok || !payload.data) throw new Error(payload.error?.message ?? "组合读取失败"); return payload.data; }).then((next) => { if (active) { setData(next); setMessage(""); } }).catch((error: unknown) => { if (active) setMessage(error instanceof Error ? error.message : "组合读取失败"); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, []);
  async function mutate(body: Record<string, unknown>) { setMessage("正在保存并重算风险…"); const response = await fetch("/api/v1/portfolio", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ portfolioId: data?.portfolio.id, ...body }) }); const payload = await response.json() as { error?: { message: string } }; if (!response.ok) return setMessage(payload.error?.message ?? "保存失败"); setMessage("已保存；仅更新行动条件，不会下单"); await load(data?.portfolio.id); }
  const allRows = useMemo<Position[]>(() => [...(data?.positions ?? []), ...(data?.watchItems ?? []).map((item) => ({ ...item, id: `watch-${item.ticker}`, positionType: "watch" as const, shares: 0 }))], [data]);

  if (!data) return <><section className="page-title workbench-title"><div><p className="section-kicker">PORTFOLIO DECISION SUPPORT / P2</p><h1>组合风险，<em>必须回到论点。</em></h1><p>持仓、暴露、压力测试与证伪条件共享同一条审计链。</p></div></section><div className="auth-banner">{loading ? "正在读取个人组合…" : message || "真实组合需要登录后使用。"}<a href="/signin-with-chatgpt?return_to=%2F">使用 ChatGPT 登录 →</a></div></>;
  const percent = (value: number) => `${(value * 100).toFixed(1)}%`;
  return <>
    <section className="page-title workbench-title"><div><p className="section-kicker">PORTFOLIO DECISION SUPPORT / P2</p><h1>看清组合风险，<em>再定义行动条件。</em></h1><p>统一持仓与观察池，追踪暴露、集中度、相关性、压力损失和论点失效。</p></div><div className="workbench-state"><span className="pulse"/>{loading ? "正在重算" : data.portfolio.name}<small>{message || `as_of ${data.asOf.slice(0, 19).replace("T", " ")}`}</small></div></section>
    <div className="execution-guard"><strong>NO AUTO-TRADING</strong><span>AlphaLens 只生成可审计的行动条件；没有券商连接器、订单对象或自动下单路径。</span><button onClick={() => mutate({ action: "risk.refresh" })}>刷新风险快照</button></div>
    {data.risk.warnings.length > 0 && <div className="risk-warnings">{data.risk.warnings.map((warning) => <span key={warning}>△ {warning}</span>)}</div>}

    <section className="metric-grid portfolio-kpis">
      <article className="metric-card"><div className="card-label">Gross / Net</div><div className="metric-main"><strong>{percent(data.risk.grossExposure)}</strong><span>/ {percent(data.risk.netExposure)}</span></div><p>总暴露 / 方向性净暴露</p></article>
      <article className="metric-card"><div className="card-label">Beta-adjusted Net</div><div className="metric-main"><strong>{percent(data.risk.betaAdjustedNet)}</strong></div><p>缺失 β 时按 1.0 降级</p></article>
      <article className="metric-card"><div className="card-label">Top 5 / HHI</div><div className="metric-main"><strong>{percent(data.risk.top5Weight)}</strong><span>/ {data.risk.hhi.toFixed(3)}</span></div><p>有效持仓数 {data.risk.effectivePositions.toFixed(1)}</p></article>
      <article className="metric-card"><div className="card-label">Correlation coverage</div><div className="metric-main"><strong>{percent(data.correlation.coverage)}</strong></div><p>{data.correlation.warnings[0] ?? "配对样本达到最低要求"}</p></article>
    </section>
    <form className="risk-policy-bar" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void mutate({ action: "policy.save", nav: Number(form.get("nav")), maxPositionWeight: Number(form.get("maxPositionWeight")) / 100, maxSectorWeight: Number(form.get("maxSectorWeight")) / 100, maxFactorExposure: Number(form.get("maxFactorExposure")) / 100, maxEventClusterWeight: Number(form.get("maxEventClusterWeight")) / 100, scenarioLossBudgetBps: Number(form.get("scenarioLossBudgetBps")), absoluteLossCapBps: Number(form.get("absoluteLossCapBps")), correlationLookbackDays: data.policy.correlationLookbackDays ?? 60, exitParticipationRate: data.policy.exitParticipationRate }); }}><label>NAV<input name="nav" type="number" min="0" defaultValue={data.policy.nav}/></label><label>单仓上限 %<input name="maxPositionWeight" type="number" min="0" max="500" defaultValue={data.policy.maxPositionWeight * 100}/></label><label>行业上限 %<input name="maxSectorWeight" type="number" min="0" max="500" defaultValue={data.policy.maxSectorWeight * 100}/></label><label>因子上限 %<input name="maxFactorExposure" type="number" min="0" max="500" defaultValue={data.policy.maxFactorExposure * 100}/></label><label>事件上限 %<input name="maxEventClusterWeight" type="number" min="0" max="500" defaultValue={data.policy.maxEventClusterWeight * 100}/></label><label>情景预算 bps<input name="scenarioLossBudgetBps" type="number" min="1" defaultValue={data.policy.scenarioLossBudgetBps}/></label><label>绝对上限 bps<input name="absoluteLossCapBps" type="number" min="1" defaultValue={data.policy.absoluteLossCapBps}/></label><button>保存风险预算</button></form>

    <section className="portfolio-layout">
      <article className="panel portfolio-book"><div className="panel-head"><div>持仓 + 观察池统一视图</div><span>{allRows.length} 个标的</span></div><div className="portfolio-table"><div className="portfolio-row header"><span>标的</span><span>状态</span><span>市值</span><span>权重</span><span>行业 / 币种</span><span>流动性</span><span/></div>{allRows.map((item) => { const weight = data.risk.weights.find((row) => row.ticker === item.ticker); const liquidity = data.risk.liquidity.find((row) => row.ticker === item.ticker); return <div className="portfolio-row" key={item.id}><strong>{item.ticker}</strong><b className={`position-${item.positionType}`}>{item.positionType}</b><span>{item.positionType === "watch" ? "—" : `$${Math.abs(item.marketValue ?? item.shares * (item.currentPrice ?? 0)).toLocaleString()}`}</span><span>{weight ? percent(weight.weight) : "—"}</span><span>{item.sector || "待分类"} · {item.currency ?? "USD"}</span><span>{liquidity?.daysToExit == null ? "待 ADV" : `${liquidity.daysToExit.toFixed(1)} 天`}</span>{item.positionType === "watch" ? <span/> : <button onClick={() => mutate({ action: "position.remove", id: item.id })}>移除</button>}</div>; })}{!allRows.length && <p className="wb-empty padded">尚无持仓或观察标的。先录入用户持仓快照；系统不会猜测账户数据。</p>}</div></article>
      <article className="panel position-entry"><div className="panel-head"><div>录入风险快照</div><span>用户输入 · 带 as_of</span></div><form onSubmit={(event: FormEvent) => { event.preventDefault(); void mutate({ action: "position.save", ticker, positionType, shares, currentPrice: price || null, marketValue: shares * price || null, sector, currency: positionCurrency, beta, advUsd: adv || null, factorExposures: parsePairs(factors), eventTags: events.split(",").map((item) => item.trim()).filter(Boolean), priceAsOf: new Date().toISOString(), dataStatus: "user_input" }); }}><div className="input-grid"><label>代码<input value={ticker} onChange={(event) => setTicker(event.target.value.toUpperCase())} placeholder="NVDA" required/></label><label>类型<select value={positionType} onChange={(event) => setPositionType(event.target.value)}><option value="long">Long</option><option value="short">Short</option><option value="watch">Watch</option></select></label><label>股数<input type="number" min="0" value={shares} onChange={(event) => setShares(Number(event.target.value))}/></label><label>价格<input type="number" min="0" step="0.01" value={price} onChange={(event) => setPrice(Number(event.target.value))}/></label><label>行业<input value={sector} onChange={(event) => setSector(event.target.value)} placeholder="Technology"/></label><label>币种<input value={positionCurrency} onChange={(event) => setPositionCurrency(event.target.value.toUpperCase())}/></label><label>Beta<input type="number" step="0.1" value={beta} onChange={(event) => setBeta(Number(event.target.value))}/></label><label>ADV USD<input type="number" min="0" value={adv} onChange={(event) => setAdv(Number(event.target.value))}/></label><label className="wide">因子暴露<input value={factors} onChange={(event) => setFactors(event.target.value)} placeholder="growth:1, quality:0.6"/></label><label className="wide">事件标签<input value={events} onChange={(event) => setEvents(event.target.value)} placeholder="earnings, regulation"/></label></div><button className="wb-primary">保存持仓快照</button></form></article>
    </section>

    <section className="wb-grid wb-grid-2">
      <article className="panel"><div className="panel-head"><div>多维暴露地图</div><span>净暴露；事件为绝对暴露</span></div><div className="exposure-columns"><ExposureGroup title="行业" values={data.risk.exposures.sector}/><ExposureGroup title="因子" values={data.risk.exposures.factor}/><ExposureGroup title="币种" values={data.risk.exposures.currency}/><ExposureGroup title="事件" values={data.risk.exposures.event}/></div></article>
      <article className="panel"><div className="panel-head"><div>相关性矩阵</div><span>用户导入日收益率 · Pearson</span></div>{data.correlation.tickers.length ? <div className="correlation-grid" style={{ gridTemplateColumns: `62px repeat(${data.correlation.tickers.length},minmax(42px,1fr))` }}><i/>{data.correlation.tickers.map((item) => <b key={`h-${item}`}>{item}</b>)}{data.correlation.tickers.flatMap((left) => [<b key={`r-${left}`}>{left}</b>, ...data.correlation.tickers.map((right) => { const value = data.correlation.matrix[left]?.[right]; return <span key={`${left}-${right}`} style={{ background: value == null ? "#151a17" : value > .7 ? "#4a633b" : value > .3 ? "#293a2d" : value < 0 ? "#3c2926" : "#202923" }}>{value == null ? "—" : value.toFixed(2)}</span>; })])}</div> : <p className="wb-empty padded">导入至少两个标的、每个不少于 20 个对齐交易日的收益率后生成相关性矩阵。</p>}<form className="returns-import" onSubmit={(event) => { event.preventDefault(); const rows = returnsText.split("\n").map((line) => line.split(",").map((item) => item.trim())).filter((row) => row.length === 3).map(([returnTicker, date, value]) => ({ ticker: returnTicker.toUpperCase(), date, returnValue: Number(value) })); void mutate({ action: "returns.import", rows }); }}><textarea value={returnsText} onChange={(event) => setReturnsText(event.target.value)} placeholder={"CSV 每行：ticker,date,daily_return\nNVDA,2026-07-17,0.012"}/><button>导入收益率</button></form></article>
    </section>

    <section className="portfolio-layout">
      <article className="panel"><div className="panel-head"><div>情景压力测试</div><span>预算 ≠ 绝对损失上限</span></div><form className="scenario-form" onSubmit={(event) => { event.preventDefault(); void mutate({ action: "scenario.run", name: scenarioName, shocks: [{ dimension: shockDimension, key: shockKey, percent: shockPercent }], asOf: new Date().toISOString() }); }}><input value={scenarioName} onChange={(event) => setScenarioName(event.target.value)} aria-label="情景名称"/><select value={shockDimension} onChange={(event) => setShockDimension(event.target.value)}><option value="sector">行业</option><option value="ticker">个股</option><option value="factor">因子</option><option value="currency">币种</option><option value="event">事件</option></select><input value={shockKey} onChange={(event) => setShockKey(event.target.value)} aria-label="冲击键"/><input type="number" min="-100" max="500" value={shockPercent} onChange={(event) => setShockPercent(Number(event.target.value))}/><button>保存版本并运行</button></form><div className="scenario-results">{data.scenarios.map((scenario) => <div key={scenario.id}><strong>{scenario.name} · v{scenario.version}</strong><span>{Math.round(scenario.result?.lossBps ?? 0)} bps</span><b className={scenario.result?.budgetStatus === "within_budget" ? "good" : "warn"}>{scenario.result?.budgetStatus ?? "待运行"}</b></div>)}{!data.scenarios.length && <p className="wb-empty">建立第一个多维冲击情景；结果按组合 NAV 计算。</p>}</div></article>
      <article className="panel action-conditions"><div className="panel-head"><div>论点 × 证伪 × 风险预算</div><span>行动条件，不是订单</span></div><div>{[...data.generatedConditions, ...data.savedConditions].filter((item, index, rows) => rows.findIndex((candidate) => candidate.message === item.message) === index).map((condition) => <article key={"key" in condition ? condition.key : condition.id} className={`condition-${condition.severity}`}><div><strong>{condition.ticker ?? "PORTFOLIO"}</strong><span>{condition.conditionType}</span></div><p>{condition.message}</p>{"id" in condition && condition.status === "triggered" && <button onClick={() => mutate({ action: "condition.acknowledge", id: condition.id })}>确认已阅读</button>}</article>)}{!data.generatedConditions.length && !data.savedConditions.length && <p className="wb-empty padded">当前没有触发的风险条件。刷新快照会保存可审计结果。</p>}</div></article>
    </section>

    <section className="panel portfolio-calendar"><div className="panel-head"><div>组合催化剂日历</div><span>只包含持仓标的 · 来源新鲜度可见</span></div><div>{data.catalysts.map((item) => <article key={item.id}><time>{item.eventAt?.slice(0, 10) ?? "TBD"}</time><strong>{item.ticker}</strong><span>{item.title}</span><b>{item.dateStatus}{item.isStale ? " · stale" : ""}</b></article>)}{!data.catalysts.length && <p className="wb-empty padded">持仓公司尚无已确认催化剂；可在 P1 工作台配置官方 IR Feed。</p>}</div></section>
  </>;
}

function ExposureGroup({ title, values }: { title: string; values: Exposure }) { const rows = Object.entries(values).sort((a, b) => Math.abs(b[1]) - Math.abs(a[1])).slice(0, 6); return <section><h3>{title}</h3>{rows.length ? rows.map(([label, value]) => <div key={label}><span>{label}</span><i><b style={{ width: `${Math.min(100, Math.abs(value) * 100)}%` }}/></i><strong>{(value * 100).toFixed(1)}%</strong></div>) : <p>待分类</p>}</section>; }
function parsePairs(value: string) { return Object.fromEntries(value.split(",").map((item) => item.split(":").map((part) => part.trim())).filter((item) => item[0] && Number.isFinite(Number(item[1]))).map(([key, number]) => [key, Number(number)])); }
